TryGhost/Ghost-CLI

- lib/commands/start.js
- package.json
Check database health before starting Ghost and run `knex-migrator` init if database was never initialised.
> ✨  use knex-migrator

- lib/commands/config/index.js
- lib/commands/install.js
- test/acceptance/config-spec.js
- Output version information when install/downloading
- Include a default when prompting for URL
Note, locally when running the tests, even on master I get a failure:
```
1) Unit: npm correctly captures the npm output and returns it when output is a string:
TypeError: this is not a typed array.
at Function.from (native)
at Context.<anonymous> (test/unit/utils/npm-spec.js:155:43)
```
> 🎨 Minor messaging improvements

- lib/commands/run.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/process/local.js
- lib/utils/resolve-version.js
- package.json
closes #66,#61
- breaking: won't work with any ghost versions < 1.0.0-alpha.8
Release once Ghost 1.0.0-alpha.8 has been released
> Updates for Ghost alpha 8

- lib/commands/doctor/checks/setup.js
- lib/commands/install.js
- lib/commands/setup.js
refs #64
- add `--no-stack` flag to install and setup commands to override system
checks
- add checks for ubuntu version, systemd, and nginx
- output helpful error message if stack is not recommended
> Add ghost system stack checks to setup

- lib/utils/npm.js
Fixes #53.
It turns out the name of the binary on Windows platforms is different to *nix platforms.
Tested on Windows 7 (~~lame~~, I mean it's kind of old, I should update it 😅 ) with Node v6.9.1 and npm v3.10.8.
Would love to hear feedbacks on how this works on other Windows platforms.
> Use `npm.cmd` instead of `npm` on Windows

- lib/process/local.js
- lib/utils/yarn.js
- test/unit/utils/yarn-spec.js
refs #104
- ensure usages of `assign` don’t overwrite existing objects
TODO:
> 🐛 don’t mutate process.env using lodash methods

- lib/commands/run.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/process/index.js
- lib/process/systemd/index.js
- lib/utils/resolve-process.js
no issue
- on non-systemd systems, the systemd process manager would still try to set itself up the normal way if the user said “Continue Anyways”
- this update allows process managers to check if they are usable on the system. If not, the process manager resolver logs a warning and defaults to the local process manager
- adds a #checkUsability function to the BaseProcess class (returns true by default)
> 🎨 ✨ improve process manager handling on unsupported environments

- lib/cli.js
- lib/commands.js
- lib/commands/ls.js
- lib/commands/run.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/ui/index.js
- lib/utils/Instance.js
- lib/utils/config.js
- package.json
- yarn.lock
Refs #65 
This PR refactors some of multi-process management handling of the CLI to better enable users to see multiple instances of Ghost running on the same system.
Additions:
~~- `ghost info <pname>` - View basic information about a running ghost process~~ punting on this one for a bit - need to figure out how to dedupe process names.
Screenshots!
`ghost ls`
`ghost stop -a`
> Multi-install management improvements

- lib/commands/start.js
refs #152
- if a development config exists but not a production one, running ghost
start without the `-D` option will still run in development mode
- fixes issues when running `ghost start` in a local install
> Make `ghost start` smarter with the node environment

- lib/commands/ls.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/utils/config.js
- lib/utils/dedupe-process-name.js
- de-duplicate process name on setup using lodash uniqueId()
- index process list by process name rather than cwd
- make Config cache files by absolute filename rather than local
- `ghost stop --all` stops all the processes in the same cli process, rather than executing subcommands.
> Various improvements around multi-install management

- lib/services/nginx/index.js
Not sure if anything else is needed here (didn't see any related tests), but this fixes a particularly annoying bug that I'd like to get sorted in a release sometime soon 😁 
closes #186
- adds a single extra line to the ssl block
- allows multiple blogs to be installed on one server
> Add server_name directive to nginx ssl block

- lib/commands/config/advanced.js
closes #184
- tighten up pname validation regex
- replace dots with dashes in default pname
> fix(ls): don't allow dots in process name

- lib/commands.js
- lib/commands/run.js
closes #185
- fix command descriptions
- output help note on `ghost run` if it is being run directly
> fix(run): make command descriptions clearer

- lib/commands.js
- lib/commands/uninstall.js
- lib/services/index.js
- lib/services/nginx/index.js
- lib/services/process/systemd/index.js
- lib/ui.js
~~Almost done - just need to test on Linux and also add a check for the nginx service so that it doesn't try to delete files that aren't there.~~ done!
closes #187
> I am become uninstall, destroyer of ghost instances

- lib/commands.js
- lib/commands/setup.js
Again, this is a proposal more than anything & not particularly well tested 😁 
refs #194
- if --start is provided, use that instead of prompting
- makes it easier to call ghost install/ghost setup programmatically
> ✨ Allow start flag to be provided, skip prompts

- lib/commands/config/advanced.js
Ghost-cli does not consider the IP address given in the '--ip' option
on the command line. Adding this line fixes the issue.
Thanks to @acburdine who responded on Slack with this solution and asked
me to submit a PR.
> Fix: IP address not configured when specified as option

- lib/commands/config/advanced.js
- lib/services/nginx/index.js
This is a proposal for how to introduce ssl config without requiring a prompt.
It is a little bit odd in that it causes the ssl email to be written to config. Not sure if that's useful/desired.
Note: I've not done particularly extensive testing of this.
refs #194
- If --sslemail is provided, use that instead of prompting
- Makes it easier to call ghost programmatically
> ✨ Allow SSL Email to be provided, skip prompts

- lib/services/nginx/files/ssl-params.conf
refs #230
*Using refs, because i would like to wait for feedback on ssl ciphers.*
- change x-frame-options from DENY to SAMEORIGIN
- SAMEORIGIN: This setting will allow the page to be displayed in a frame on the same origin as the page itself.
- background: if we deny x-frame-options, we can't export content/database
@ErisDS I have talked to @acburdine quickly, we can merge this already into master and @acburdine will rebase his [extension PR](https://github.com/TryGhost/Ghost-CLI/pull/238) against master.
> 🎨  X-Frame-Options SAMEORIGIN

- lib/commands/config/advanced.js
refs #232, #216
- this is the most straight forward pass through adding mail config options
- there is loads of small tweaks possible here, but they are not required
E.g.
- auto-set transport to smtp if any other argument is supplied
- use grouping to make the output better
- stronger use of implies?
---- 
This makes it possible to configure SMTP & Sendmail transports via the CLI using `--mail`. [SES and Pickup](https://github.com/nodemailer/nodemailer/tree/0.7#possible-transport-methods) are not supported as transports. Direct doesn't require further config.
This then makes it possible to provide the most common other options for SMTP. Sendmail options are all optional, so we don't support these via the cli.
Any more advanced SMTP or optional Sendmail config can be provided by editing …
> ✨ Accept mail configuration options

- lib/commands/config/advanced.js
Don't think we should keep this around?
no issue
- auth is no longer going to be used
- as we don't want anyone to use it, we shouldn't output it in help :)
> 🔥 fix(config): remove unused auth option

- extensions/systemd/systemd.js
- lib/commands/restart.js
- lib/process-manager.js
- test/unit/commands/restart.js
- test/unit/process-manager.js
no issue
- add optional restart method to process managers that will, by default, just run the stop & start methods of the process manager in sequence. However, process managers can choose to override this with a custom implementation that is more suited to their individual setups
> feat(process): improve restart flow

- extensions/nginx/index.js
- extensions/systemd/index.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/uninstall.js
- lib/commands/update.js
- lib/tasks/migrate.js
- test/unit/tasks/migrate-spec.js
closes #250
- clean up contextual instance behavior in setup tasks
- move migrate task into setup & update commands rather than start commands
> refactor(migrate): move migrations step into setup & update commands

- extensions/systemd/systemd.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/process-manager.js
- test/unit/process-manager-spec.js
closes #248
- add isEnabled, enable, disable methods to process manager
- add support for enable/disable to start and stop commands
TODO:
> feat(process): add enable/disable support

- extensions/nginx/index.js
- lib/commands/setup.js
This PR covers two things:
1. Running of multiple setup stages with one command (e.g. `ghost setup nginx ssl systemd`). This addition will also preserve stage order, so if you type `ghost setup ssl systemd nginx`, it will still run in the right order (`nginx`, `ssl`, then `systemd`).
2. Addition of stage "dependencies". A stage can depend on other stages having run, and two things can occur if a dependent stage hasn't run yet:
- ~~If the user is running individual stages (e.g. `ghost setup stage1 stage2`), and the dependent stage is not in the list & has not yet been run, it will automatically be added to the list~~ (nixed, too complex)
- if the user is running the general setup command and the stage has been skipped, the stage that depends on it will also be skipped, with a message …
> More work on setup stages

- lib/instance.js
- test/unit/instance-spec.js
no issue
- fix usage of --no-prompt with instance#template method
> fix(instance): don't prompt for templates if prompts are disabled

- lib/commands/doctor/checks/install.js
- lib/errors.js
- lib/ui/index.js
refs #216
- adds message "Please refer to https://docs.ghost.org for troubleshooting." to CliError as `help` property.
- adds the same message to the ui handling for native JS errors.
- changes the link for supported node versions to the docs
> 📖  Add troubleshooting link to errors

- extensions/nginx/index.js
closes #231
refs #216 
Adds `client_max_body_size 50m;` to nginx default config file.
I tested this successful on a DO droplet.
> 🙈  Add `client_max_body_size` to nginx default config

- lib/command.js
refs #236
refs #216
Logs a more useful error warning, if user attempts to use Ghost-CLI within a LTS installation. Indicator for LTS installation is the presence of a `config.js` file.
> 👀  Log LTS warning when `config.js` file is found

- lib/commands/start.js
refs #216
- adds a little ui message to guide people towards docs for mail config
> Add mail config message after installation

- extensions/mysql/index.js
- extensions/mysql/package.json
- lib/commands/doctor/checks/setup.js
- lib/errors.js
- package.json
- yarn.lock
refs #191 
- If the mysql `ghost` user exists, the CLI can detect that, but that's it - we won't be able to figure out the password - so imagine you run `ghost setup` twice. on the first run the CLI creates the mysql user and stores this user inside the config.production.json. Then the user manually deletes this file. And he runs `ghost setup` again, he enters the root credentials again. The CLI would detect that the custom mysql user exists, but without a password, we can't do anything. Edge case?
- there is a tricky case: imagine we have created the mysql user for you. the ghost user is part of the config file. alright, now you re-run `ghost setup` and change the database name. You can't change your privileges without the root credentials, we would have to prompt the credentials again.
> Mysql extension

- lib/commands/config/index.js
- lib/commands/uninstall.js
closes #276, refs #280
- fix various instances where the --no-prompt option was not correctly respected,  resulting in an error
> fix(prompt): respect `--no-prompt` option in other areas

- extensions/linux/index.js
- extensions/linux/package.json
- extensions/systemd/index.js
closes #189
- add linux extension that creates a `ghost` user on the system, used by systemd (and potentially any other process manager)
> feat(linux): add linux user extension

- extensions/nginx/commands/ssl-renew.js
- extensions/nginx/index.js
- extensions/nginx/letsencrypt.js
no issue
- downloads acme to local install rather than global folder
- cleans up error handling so we don't throw a ProcessError if we get an error from download
> fix(ssl): fix acme.sh location and cleanup error handling

- extensions/linux/index.js
- lib/commands/install.js
- lib/commands/update.js
closes #290
- change ownership of content and versions directory only
- don’t add current user to ghost group
> Permissions

- extensions/systemd/get-uid.js
- extensions/systemd/index.js
- extensions/systemd/systemd.js
closes #291
- add function to double check that linux-user has been run
- make help messaging more clear
> fix(systemd): improve setup checks of extension and process manager

- extensions/systemd/systemd.js
closes #293
- expands error message regex to also check for failed unit file state
cc @sebgie would be good to get your eyes on this - i'm not sure if there's any other potential implications of this change.
my thought is that the enable check is somehow running before ghost has completely started, leading to the "failed to get unit file state" error, but I could be wrong.
> fix(systemd): update is-enabled error handling to be better

- extensions/nginx/index.js
no issue
- pass all request from 80 and 443 through to Ghost and let it do it’s
thing
> Remove special SSL handling

- extensions/nginx/index.js
- extensions/nginx/letsencrypt.js
closes #309
- if a user deletes their instance and recreates it with the same domain, then acme will fail to generate the certificate because it already exists & is not due for renewal. We work around this issue by looking for the error and copying the right keys if it already exists
closes #302 
- checks if ssl has already been setup, if it has then skips
- better cleanup/handling of well-known config block
> Various SSL setup fixes

- lib/commands/run.js
- lib/tasks/migrate.js
- test/unit/tasks/migrate-spec.js
closes #307
- instead of mutating process.env, set the contentPath in config if it does not exist
> fix(run): set content path in config rather than in environment

- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/commands/uninstall.js
- lib/ui/index.js
refs #313
This removes the prompt for enabling as described in #313 and also deals with the slightly weird start command, as mentioned in https://github.com/TryGhost/Ghost-CLI/pull/246
- the `ghost setup --start` flag
- The default value for "start" is "prompt"
- The fallback default value for "start", if it's not allowed to prompt is true
- Passing --no-start will set start to false, and not prompt
- Passing --start will set start to true, and not prompt
- the `ghost start --enable` flag
- Enabling doesn't trigger any prompt
- The default value for "enable" is true
- Passing --enable doesn't change anything
- Passing --no-enable prevents enabling
- calling `ghost uninstall` will now call `ghost stop --disable`
----
This caused a bug with `stopping ghost` outputting multiple times
closes …
> 🎨 fix(ui): fixes to --start --enable and --quiet flags

- lib/ui/index.js
- package.json
- test/unit/ui/index-spec.js
- yarn.lock
no issue
- deps: log-symbols@1.0.2
- ui.success and ui.fail output symbols now
> fix(ui): make fail and success methods to output symbols

- extensions/systemd/index.js
- lib/instance.js
- test/unit/instance-spec.js
Note: I'm not sure the ui.log thing here is the correct pattern. It outputs without a checkmark/tick, and looks a bit weird.
refs #313
- don't allow users to skip, as this would break things
- only show the option to continue, view or edit if --verbose is passed and --no-prompt is not
- reword the question to be would you like to view or edit
- fix the duplicate word "file" for systemd
- add a ui.log for creating the files
- TODO: use a checkmark?!
> fix(ui): 🎨 template prompt adjustments

- lib/commands/config/index.js
- lib/commands/setup.js
- lib/instance.js
- test/unit/instance-spec.js
These are just a few tiny issues I noticed while testing #338 
- don't prompt for mysql if we shouldn't prompt for mysql (boolean logic is fun)
- make start/no-start work as intended
- log successful template generation regardless if linked to system dir or not.
> Various fixes

- lib/commands/config/advanced.js
closes #349
- add defaultValue function to dbpath argument
TODO: do a quick sanity check locally and on ubuntu
> fix(config): add default dbpath when db is sqlite

- lib/utils/local-process.js
> fix(windows): fix local process manager on windows

- lib/utils/local-process.js
closes #368
- force killing on mac/linux doesn't allow the child process (ghost run) to kill the ghost server process, resulting in a orphan process that the user has to kill manually
- on windows force: true works because fkill kills the process tree, which includes the ghost server
--
> fix(local): only force kill on Windows

- lib/commands/update.js
closes #364
- if an instance was installed with a pre-stable version of Ghost-CLI, this message is output so that people know they need to do things to update their instance to work with the newest CLI version
> feat(update): add pre-stable warning message with docs link

- lib/command.js
- lib/commands/install.js
- lib/commands/update.js
This can wait - I've just had it sat around, not sure if it's desirable, but I can never remember whether its `ghost update` or `ghost upgrade` 🙈 
- main task here was to add upgrade as an alias of update
- also added my fave typo of intsall 😁
> feat(help): custom aliases

- lib/bootstrap.js
After seeing #375 I realised I find myself constantly having to lookup the `ls` command when I really just want to see the `status` of the running instances.
> feat(help): status alias

- lib/tasks/migrate.js
closes #378
- don't ignore stdout, as knex errors are written to it
> fix(migration): don't hide migration errors

- lib/commands/config/advanced.js
closes #383
- remove extra text from QQex so that it can be validated
- add GoDaddy, GoDaddyAsia and GoDaddyEurope
- add FastMail
- official list: https://github.com/nodemailer/nodemailer/blob/0.7/lib/wellknown.js
> fix(config): Allow all wellknown mail services

- lib/commands/doctor/checks/install.js
- test/unit/commands/doctor/install-spec.js
closes #405
- skip directory check if `--no-setup-linux-user` option is passed
This is a split-out from #409 -> this change is a bugfix whereas the changes in the other PR would require a minor version bump.
> fix(doctor): skip parent folder perm check if linux user is skipped

- lib/utils/use-ghost-user.js
- test/unit/utils/use-ghost-user-spec.js
closes #400
- for `id -u ghost` -> centos returns "No such user" - this made the use-ghost-user check fail
> fix(linux): make ghost user regex check case insensitive

- lib/commands/install.js
- test/unit/commands/install-spec.js
closes #423
- `ghost install 1.x.x --local` now works for local installs
TODO:
> feat(install): allow local installs to specify version

- lib/commands/config/advanced.js
TODO:
closes #421
- uses toLowerCase() and lists all config options in lowercase
> fix(config): 🐛  don't enforce case for mail config

- lib/commands/doctor/checks/install.js
- test/unit/commands/doctor/install-spec.js
closes #281
- skip directory check if `--no-setup-linux-user` option is passed
- throw error if npm bin directory is not the same as the one used to install ghost-cli
TODO:
> fix(doctor): add install checks for various nvm edge cases

- lib/commands/doctor/checks/startup.js
- test/unit/commands/doctor/startup-spec.js
closes #436
- if environment is not passed in startup context,
run checkValidInstall and checkEnvironment to ensure we run this correctly
TODO:
> fix(doctor): ensure `ghost doctor startup` works on its own

- lib/commands/log.js
- lib/commands/restart.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/commands/uninstall.js
- lib/commands/update.js
- lib/instance.js
- lib/system.js
- test/unit/commands/restart-spec.js
- test/unit/instance-spec.js
- test/unit/system-spec.js
refs #435
- instead of using a getter/setter to determine running, make it a function. This allows any errors that occur during the isRunning check to not be swallowed, plus it makes the code a little cleaner.
> fix(instance): make running a function rather than a get/set

- extensions/mysql/index.js
- extensions/mysql/test/extension-spec.js
closes #396
- on some systems, creating a password with IDENTIFIED BY doesn't work correctly, so we make the queries a bit more reliable on individual systems
TODO:
> fix(mysql): improve reliability of user creation queries

- lib/commands/update.js
- test/unit/commands/update-spec.js
This PR removes old Ghost versions during `ghost update`, keeping only the most recent 5 versions.
It also adds a bunch of tests 😁 
TODO:
> Remove old Ghost versions during `ghost update`

- lib/bootstrap.js
- lib/command.js
- lib/commands/doctor/checks/install.js
- lib/commands/update.js
- lib/errors.js
- lib/tasks/migrate.js
- lib/ui/index.js
We have changed docs.ghost.org to have 2 distinct versions, 
docs.ghost.org/v0.11/
and 
docs.ghost.org/v1
The old full-semver v1.0.0 is going away, as it doesn't make sense when we're on 1.6.x etc, we're still in the v1 stream and unlike the theme docs, the main install docs don't change from version to version in that way, instead they improve over time.
Therefore, I've updated all the occurrences in this codebase to point to docs.ghost.org/v1/docs, which should ensure their longevity and correctness!
no issue
- We've now got a standard /v1/ version of docs.ghost.org
- Using this ensures that the URLs are always correct, and users end up on the right version of the document
> chore(docs): Updated all docs urls to use /v1/

- lib/commands/config/advanced.js
- test/unit/commands/config-spec.js
closes #451 
When you use `ghost install` and specify the blog url without a port number, BASE_PORT is treated as a string so that, by the third blog instance, it fails as it has tried ports: 2368, 23681, 236811 (which is > 65535). Changing BASE_PORT to be an integer fixes the problem.
Debug Information:
Node Version: v6.11.2
Ghost-CLI Version: 1.1.0
Environment: production
Command: 'ghost install'
Please refer to https://docs.ghost.org/docs/troubleshooting#section-cli-errors for troubleshooting. and specify a blog url without a port number, BASE_PORT is treated as a string so by the third installation it fails as it tried port 2368, then 23681, then 236811 (which is greater than 65535).
> Fixed bug where BASE_PORT is appended to instead of incremented by one

- lib/commands/config/index.js
Names the default mysql database to be `ghost_environment_foldername`.
e.g. If you run `ghost install` in `/var/www/tom` then the default database name will be `ghost_production_tom`.
closes #453
> Offer better default database name when installing

- lib/command.js
- Fixes TryGhost/Ghost#8948
- Using v0.x URL (https://docs.ghost.org/v0.11/docs/migrating-to-ghost-version-100) over v1.x (https://docs.ghost.org/v1/docs/migrating-to-1-0-0) since the install is assumed to be 0.x
> Update migration docs URL

- README.md
- lib/ui/index.js
- Normalized explicit versioning (from `1.0.0` to `1.0`)
- docs and v1 was flipped for another URL
> Update typos in docs URLs

- lib/commands/config/index.js
- test/unit/commands/config-spec.js
closes #479
- the `--port` option is handled as an integer, which was causing the `value.length` check to fail. Now we cast it to a string and check the length
> fix(config): ensure non-string args are handled correctly

- lib/commands/setup.js
Now it is possible to pass both `--no-prompt` and `--no-start` options.
Before this fix `--no-start` was ignored if `--no-prompt` is present.
It’s very annoying when building containers with Ghost.
> fix(setup): don’t rewrite no-start option when no-prompt is passed

- lib/commands/config/index.js
- test/unit/commands/config-spec.js
If installing Ghost from a folder with a period in its name, for example:
```bash
$ cd example.com
$ ghost install -V
```
The default database name used will contain a period, for example `ghost_production_example.com`.
However, Ghost-CLI will then fail when it attempts to grant permissions to its new user.
This PR strips undesirable characters out of the DB name.
> Strips undesirable characters out of DB name

- package.json
For node Boron (v6), the [docs](https://docs.ghost.org/docs/supported-node-versions) say there's only support for >=6.9. The CLI checks the node version based on [package.engines.node](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/commands/doctor/checks/install.js#L51) which requires >= 6.5. This pull request fixes this discrepancy. Issue initially discovered by fredylg on Slack
> Update supported node versions

- lib/commands/config/index.js
- lib/commands/setup.js
- test/unit/commands/config-spec.js
closes #265
- add ignoreEnvCheck flag to config command
- fix tests
- fix prompts to skip mysql prompts if sqlite is defined in config already
> fix(config): run environment check when not part of ghost setup

- .travis.yml
- package.json
To comply with the following statement found in [supported-node-versions](https://docs.ghost.org/docs/supported-node-versions).
`Ghost 1.0.0 currently supports Node versions 8.8+, 6.9+ and 4.5+ only.`
> Updated package.json to add support for Node v8.8+

- lib/ui/renderer.js
The `trim` method removes linebreaks by default so `split('\n')` would do nothing
> Remove redundant linebreak filter

- package.json
No issue
[Ghost](https://github.com/TryGhost/Ghost/blob/89e57ad6b298319123802de453ef40d0d813b1df/package.json) and the [docs](https://docs.ghost.org/docs/supported-node-versions) suggest support for ^8.9.0, not ^8.8.0
> Fix Node 8 compatibility

- lib/commands/doctor/checks/install.js
- lib/tasks/migrate.js
- package.json
- test/unit/commands/doctor/install-spec.js
- yarn.lock
refs #503
- use knex-migrator version installed with Ghost itself
- remove global knex-migrator dependency
- remove "same node version" check
> feat(db): remove knex-migrator dep, use one installed with Ghost

- lib/commands/config/advanced.js
closes #519
- `ghost install` -> uses the next available port (starts with 2368)
- `ghost install --url http://localhost:4000` (uses 4000)
- `ghost install --url http://localhost:4000 --port 2390` (uses 2390 and saves localhost:2390)
> fix(config): ports work again

- extensions/nginx/test/extension-spec.js
ref #541 
- I forgot to clear out a couple of todos earlier, that's done now
- Add migration tests. In order to future proof, there are 2 describes - as time goes on we can add / remove  tests specific to each migration
> Fix up nginx tests

- package.json
Currently, test files (`*-spec.js`) are tested for coverage in nyc. This isn't necessarily something that should be done, since the goal of tests is to execute core files, and certain areas _should not_ be run.
Ref: #541 (kind of)
Full documentation available in [nyc readme](https://github.com/istanbuljs/nyc#excluding-files)
> Don't check coverage on test files

- extensions/systemd/test/systemd-spec.js
I feel like there's some repetition, so if you have any suggestions, feel free to comment!
ref: #541
> chore(tests): add systemd process manager tests

- extensions/mysql/index.js
- extensions/mysql/test/extension-spec.js
- package.json
- yarn.lock
closes #511 
This is a combination of my own commit and the commit from #534 
TODO:
> Fix generated mysql user compatibility with secure installations

- lib/commands/config/index.js
closes #508
- change default dbname format to `<folder>_<environment>` rather than `ghost_<environment>_<foldername>`
> fix(config): shorten default database name

- lib/commands/update.js
- test/unit/commands/update-spec.js
closes #481
- add a --no-restart option to the update command that skips the restart task
> feat(update): add option to disable restart on update

- extensions/nginx/index.js
- extensions/nginx/test/extension-spec.js
closes #301
- detect if the url is an IP address and skip if it is
> fix(nginx): skip SSL setup if url is an IP address

- lib/commands/log.js
closes #432
- add an error flag that loads the error log as opposed to the full access log
TODO:
- add tests for error flag
> feat(log): add --error flag to `ghost log`

- extensions/nginx/migrations.js
- extensions/nginx/test/fixtures/old-ssl-with-le.txt
- extensions/nginx/test/fixtures/ssl-without-le.txt
- extensions/nginx/test/migrations-spec.js
closes #552
- skip ssl migration in a couple more cases
TODO:
- manual test all the things
> fix(ssl-migration): make the checks for migrating ssl more robust

- bin/ghost
- lib/command.js
- lib/commands/install.js
- lib/commands/migrate.js
- lib/commands/setup.js
- lib/commands/update.js
- lib/utils/update-check.js
- test/unit/command-spec.js
- test/unit/utils/update-check-spec.js
closes #565, #563
- move update check further into the stack behind a "checkVersion" command flag
- rewrite checkUpdate class to use UI instace
- update tests
> fix(update-check): only run update check on specific commands

- lib/commands/setup.js
- test/unit/commands/setup-spec.js
closes #576
- the url was getting sanitized (e.g. swapping out `.` with `-`), but if --pname was passed it wasn't getting the same treatment. This fixes that issue.
TODO:
> fix(setup): ensure --pname arg is sanitized

- lib/utils/update-check.js
- test/unit/utils/update-check-spec.js
closes #563
- remove prompt on update-check because it was bad UX & broke docker
> fix(update-check): remove prompt if version is out-of-date

- lib/command.js
- lib/commands/version.js
- lib/utils/check-root-user.js
- test/unit/command-spec.js
- test/unit/utils/check-root-user-spec.js
refs #47
- adds a `checkRootUser` fn to our base command class, which prevents any command to be run as `root`
- adds test
> feat(command) prevent commands run as root user

- extensions/nginx/acme.js
- extensions/nginx/test/acme-spec.js
- lib/errors.js
- test/unit/errors-spec.js
refs #587
- fixes an issue, where failed requests with `got` wouldn't get catched properly
- differentiates between `ProcessError` for `stderr` and `CliError` for everything else
- `CliError` can be passed the original error and will log the `message` and `stack` to the log file, or log in the UI when in verbose mode
- Adds `err` property with original error whereever we have it so it'll be passed along and printed in the log file
> feat(ssl) improve error messages to log original error

- lib/utils/check-root-user.js
- test/unit/utils/check-root-user-spec.js
- windows doesn't have a getuid function, so we don't want to check it if we're on windows
> fix(windows): don't check for root user on windows

- lib/utils/local-process.js
- test/unit/utils/local-process-spec.js
closes #501
- if the content folder is owned by a separate user, the local process manager will fail
- improve local process manager errors
- add local process manager tests
> fix(local-process): error if content folder owned by other user

- lib/instance.js
- test/unit/instance-spec.js
closes #463
- query each process manager if running is not set in cli config
> fix(instance): query process managers in dev & prod if running not set

- lib/commands/doctor/checks/content-folder.js
- lib/commands/doctor/checks/index.js
- test/unit/commands/doctor/checks/content-folder-spec.js
refs #47
- adds a new task to `ghost doctor startup` which runs on `ghost start`
- skips this task if
- ghost user is not setup or
- ghost user doesn't own the content folder
- checks the permissions inside the content folder and fails if a file or directory is not owned by ghost
- logs the relevant files or directories
- adds tests
> feat(doctor) content folder permission checks

- extensions/systemd/systemd.js
- extensions/systemd/test/systemd-spec.js
- lib/commands/run.js
- lib/process-manager.js
- lib/utils/port-polling.js
- test/unit/commands/run-spec.js
- test/unit/utils/port-polling-spec.js
closes #472
- added port polling utility
- general process manager class offers `ensureStarted` function
- systemd extension makes use of `ensureStarted`
> feat(core): Ensure that Ghost was started

- lib/commands/doctor/checks/check-permissions.js
- lib/commands/doctor/checks/content-folder.js
- lib/commands/doctor/checks/file-permissions.js
- lib/commands/doctor/checks/index.js
- lib/commands/doctor/checks/install-folder-permissions.js
- test/unit/commands/doctor/checks/check-permissions-spec.js
- test/unit/commands/doctor/checks/content-folder-spec.js
- test/unit/commands/doctor/checks/file-permissions-spec.js
- test/unit/commands/doctor/checks/install-folder-permissions-spec.js
- test/unit/utils/port-polling-spec.js
refs #47
closes #294
- Renames `folderPermissions` to `installFolderPermissions`
- Adds two more tasks: `filePermissions` and `folderPermissions` which check for the correct permissions inside of the ghost installation folder
- not enabled when local processmanager is used (= local install)
- calls `checkPermissions` util
- `filePermissions` does not check the versions and current folder
- Refactors the `contentFolderPermissions` to be named `contentFolder` and disables task when content folder is not owned by ghost or ghost user is not found.
- Adds `checkPermissions` util which takes a property to specify which check should run:
- `owner` checks for ownership of the content folder
- `folder` checks if directories within the ghost installation folder have the correct permission (775)
- …
> feat(doctor) detect incorrect permissions

- .github/ISSUE_TEMPLATE.md
- lib/commands/doctor/checks/system-stack.js
- lib/system.js
- lib/ui/index.js
- lib/utils/get-os.js
- test/unit/system-spec.js
- test/unit/ui/index-spec.js
- test/unit/utils/get-os-spec.js
no issue
- added a new getter to the System class, that returns the operating system as well as the version
- works for linux, mac, and windows. Everything else falls back to the native `os.platform()` fn.
- prints the os and the version in the debug information
- added tests
> feat(system) add os and version to System class

- lib/commands/doctor/checks/validate-config.js
- test/unit/commands/doctor/checks/validate-config-spec.js
- test/unit/utils/resolve-version-spec.js
no issue
- skips the validate config check when the tested instance is currently running, as it would fail for testing the server port
> fix(doctor) skip validate config check for running instances

- extensions/systemd/systemd.js
- extensions/systemd/test/systemd-spec.js
> fix(systemd) improve systemd precheck error messages

- lib/commands/doctor/checks/install-folder-permissions.js
no issue
- show clearer error message and help link to the docs, when install directory doesn't have the right permissions
> feat(doctor) show help message for install folder checks

- lib/utils/update-check.js
- test/unit/utils/update-check-spec.js
no issue
- if we want to be able to push prereleases in the future, this is a necessary addition to the update check
> fix(update-check): don't warn for prerelease or build

- lib/command.js
- lib/utils/check-root-user.js
- test/unit/utils/check-root-user-spec.js
no issue
- detect DigitalOcean One-Click install and render a message how to migrate their installation to a non-root user
> fix(root-user): show different error message for 1-click installs

- lib/utils/check-root-user.js
- test/unit/utils/check-root-user-spec.js
no issue
- if outside of a root install (or a root install has been fixed),
commands will still fail as root
> fix(root-user): only skip exiting inside root install

- extensions/nginx/test/acme-spec.js
- extensions/nginx/test/extension-spec.js
- extensions/nginx/test/migrations-spec.js
- extensions/systemd/test/systemd-spec.js
- test/unit/commands/config-spec.js
- test/unit/commands/log-spec.js
- test/unit/commands/setup-spec.js
- test/unit/commands/start-spec.js
- test/unit/commands/stop-spec.js
- test/unit/commands/uninstall-spec.js
- test/unit/tasks/yarn-install-spec.js
- test/unit/ui/index-spec.js
- test/unit/utils/find-extensions-spec.js
- test/unit/utils/yarn-spec.js
No issue
- Just standardizing the mechanism to retrieve a specific call
> chore(tests): use args[n][m] instead of getCall(n).args[m]

- lib/commands/uninstall.js
- test/unit/commands/uninstall-spec.js
closes #577
- cleanup uninstall tests
- disable remove content folder step if ghost user doesn't own content folder
> fix(uninstall): only use sudo to remove content folder when needed

- lib/utils/port-polling.js
Doubled timeout to allow the CLI tool to run on slower devices, like the Raspberry Pi. Whilst not officially supported, Raspbian Stretch does work with the new Ghost CLI tool with a few tweaks. Recent changes to the CLI tool (this check) caused the install / update process to fail due to the timeout check. Discussed with Vilkas Potluri in the Slack Help channel (under my username GhostPi) and this works. Tested on 4 blogs hosted on my own Raspberry Pi. Linked to issue opened (and subsequently closed) found here: https://github.com/TryGhost/Ghost/issues/9447#event-1465916582
> Update port-polling.js to allow Ghost-CLI to work on slower devices (Raspberry Pi et al).

- lib/process-manager.js
- lib/utils/port-polling.js
- test/unit/process-manager-spec.js
- test/unit/utils/port-polling-spec.js
closes #643
- if the host is specified and isn't 0.0.0.0, use the custom host, otherwise use localhost
> fix(port-polling): connect over custom host if custom host is specified

- lib/bootstrap.js
- lib/utils/find-extensions.js
- package.json
- test/unit/utils/find-extensions-spec.js
- yarn.lock
no issue
- increase startup perf time by not shelling out to npm and instead using 'global-modules'
- add extra bootstrap cli debug statement to see startup times more accurately
Came across this as I was doing some work on the command loading section - this should make startup times a _bit_ quicker. Here are some results based on some initial testing I did (2017 mbp - 16gb ram):
Before this change:
```
acburdine@Austins-MacBook-Pro ~/Projects/Ghost/cli  (master *) $ DEBUG=ghost-cli:* ghost -v
ghost-cli:bootstrap Starting bootstrap process +0ms
ghost-cli:find-extensions searching for extensions +0ms
ghost-cli:bootstrap Found 4 extensions: ... +454ms
ghost-cli:bootstrap loading built-in commands +1ms
ghost-cli:bootstrap loading commands from extensions +0ms
ghost-cli:bootstrap discovered …
```
> perf(bootstrap): swap out `npm root` call for global-modules dep

- lib/commands/restart.js
- lib/commands/start.js
- lib/commands/stop.js
- test/unit/commands/restart-spec.js
- test/unit/commands/start-spec.js
- test/unit/commands/stop-spec.js
closes #649 
- `ghost stop` notifies user and exits if instance is already stopped
- `ghost start` notifies user and informs of `ghost ls` command for more information
- `ghost restart` notifies user and runs start command if instance is not running already
There's another PR coming up to finish the minor refactor of the restart command!
> feat: make ghost (stop | start |  restart) more graceful

- test/unit/commands/restart-spec.js
(kind of) depends on #650 
- Remove unneeded class-based stubs
- Was originally introduced in 650 to reduce unnecessary requires
> Refactor restart tests

- package.json
- test/unit/ui/renderer-spec.js
- yarn.lock
Running separately from #663 since semver change is major (1.4.0 -> 2.0.0)
/cc @JohnONolan can you verify #446 no longer occurs with this update? After updating ora the issue vanished 😄
> chore(deps): update ora (closes #446)

- lib/commands/doctor/checks/validate-config.js
- lib/commands/log.js
- lib/commands/ls.js
- lib/commands/restart.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/commands/uninstall.js
- lib/commands/update.js
- lib/instance.js
- lib/process-manager.js
- lib/system.js
- test/unit/commands/doctor/checks/validate-config-spec.js
- test/unit/commands/log-spec.js
- test/unit/commands/ls-spec.js
- test/unit/commands/restart-spec.js
- test/unit/commands/start-spec.js
- test/unit/commands/stop-spec.js
- test/unit/commands/uninstall-spec.js
- test/unit/commands/update-spec.js
- test/unit/instance-spec.js
- test/unit/process-manager-spec.js
- test/unit/system-spec.js
refs #668 
- update instance.running() to handle process.isRunning promise
- update everywhere that uses instance.running to handle the promise
TODO:
- See #668 - it would be useful to allow process.isRunning to return a promise.
> feat(process-manager): allow process isRunning to return a promise

- lib/commands/start.js
- lib/commands/stop.js
- test/unit/commands/start-spec.js
- test/unit/commands/stop-spec.js
refs #672
- support isEnabled returning a promise
> feat(process): allow process.isEnabled to return a promise

- lib/bootstrap.js
no issue
- this helps keep the output clean, most of the aliases are either abbreviations or recognized typo commands
> fix(help): don't show aliases on help output

- extensions/systemd/systemd.js
- extensions/systemd/test/systemd-spec.js
closes #660 
refs #414
Recently there were many users reporting issues when the CLI is running the command `systemctl is-active`. With the changes in #669 we are now able to run the `isRunning` and `isEnabled` methods in our systemd extension, as those were the only commands that weren't executed as `sudo`.
Manual tests worked fine for me. I can't say if it'll fix all the issues, as I wasn't able to reproduce the issues on the recommended stack. Nevertheless, there were enough reports of this issue actually happening *on* the recommended stack.
> Run `isRunning` and `isEnabled` as sudo

- lib/commands/ls.js
- test/unit/commands/ls-spec.js
no issue
Currently, when a user runs `ghost ls` and has no installed ghost instances, they just get a table header. This  can be confusing, so instead, we're outputting a more informative message of "No installed ghost instances found"
> feat(ls command): don't render table when no instances found

- lib/commands/setup.js
- test/unit/commands/setup-spec.js
closes #615
- respect no-start in local installs
- fix ui.confirm usage
> fix(setup): fix start/no-start option

- extensions/mysql/index.js
- extensions/mysql/test/extension-spec.js
- extensions/nginx/index.js
- extensions/nginx/test/extension-spec.js
- extensions/systemd/get-uid.js
- extensions/systemd/index.js
- extensions/systemd/systemd.js
- extensions/systemd/test/extension-spec.js
- extensions/systemd/test/get-uid-spec.js
- extensions/systemd/test/systemd-spec.js
refs #587 
Trying to get a better error handling for our extensions. Catches an error whenever there was no catch, but one needed, creates proper errors when they were just thrown.
> Improve error messages in extensions

- lib/commands/doctor/checks/index.js
- lib/commands/doctor/checks/logged-in-user.js
- test/unit/commands/doctor/checks/logged-in-user-spec.js
refs #47
- Adds a check to the `install` category
- Check is disabled for local installs and platforms that are not linux
- Check will prevent user from installation, if the `ghost` user exists and user is logged in as such
- Adds tests. Still 💯
Outcome:
> feat(doctor): prevent installations with ghost user

- lib/commands/doctor/checks/logged-in-ghost-user.js
No issue
I was just updating an instance and looking over the command history. I was confused as to why the `Checking if user is logged in with ghost user` task passed, since I wasn't logged in as ghost. It took me a minute to realize the task was checking that the current user _isn't_ ghost. This PR updates the wording to convey the message
> chore(doctor): use more informative task title for checking ghost user

- lib/commands/run.js
- test/unit/commands/run-spec.js
Refs #691 and closes #690
This was added in the past to ensure contentPath will be valid for ghost. Given the contentPath is set (if not already) in the migrate step, this extra check causes invalid, manually edited configuration to be overwritten with a (basically) empty file. Since a lot of people test their config by restarting ghost, this hurts more people than it helps
> fix(run): Don't set contentPath in config when running

- lib/migrations.js
- lib/tasks/ensure-structure.js
- test/unit/migrations-spec.js
- test/unit/tasks/ensure-structure-spec.js
refs TryGhost/Ghost#9528
- adds `content/settings` folder to install process (for new installations)
- adds a core migration that makes sure, `content/settings` exists (for older installations)
----
> Ensure `content/settings` folder

- lib/utils/version-from-zip.js
- test/unit/utils/version-from-zip-spec.js
refs #681
refs #587
Give the user more information why the installation of the zip file failed. Renders the required and the current installed CLI version and the command to run to solve the issue.
Looks like this:
> chore(utils): improve error message for incompatible ghost zip

- lib/commands/doctor/checks/install-folder-permissions.js
- test/unit/commands/doctor/checks/install-folder-permissions-spec.js
closes #711 
We successfully pass this check for the `ghost install local` command and the intention was to always pass/skip it for local installs. The `local` argument is only available when executing the installation command. But this check also runs for `ghost start` and `ghost update` when there's no `local` argument.
This change will skip the check now also when the local process manager is used, which usually means that it's a local installation.
> fix(doctor): skip install dir checks for local installs

- lib/commands/start.js
- test/unit/commands/start-spec.js
closes #665
- added a new message that shows the URL to the admin interface
- uses custom admin URL, if set in config
- shows a slightly different message when rendered after the `install` process
> feat(start): direct user to admin interface

- lib/tasks/linux.js
- test/unit/tasks/linux-spec.js
closes #676
- an error thrown in this place essentially means there's no user, so the strict error message checking is unnecessary and breaks systems in which the id message is different
> fix(linux): remove strict no such user error message checking

- lib/tasks/migrate.js
- test/unit/tasks/migrate-spec.js
refs #708
- this was from the days where we executed knex-migrator directly. We no longer do that, so suppressing the knex-migrator command output is no longer necessary
todo:
> fix(migrate): remove unnecessary config overwrite during db migrations

- lib/tasks/yarn-install.js
- test/acceptance/install-local-spec.js
- test/unit/bootstrap-spec.js
- test/unit/commands/doctor/checks/validate-config-spec.js
- test/unit/commands/update-spec.js
- test/unit/tasks/ensure-structure-spec.js
- test/unit/tasks/yarn-install-spec.js
- test/utils/acceptance-test.js
- test/utils/test-folder.js
refs #726 
- if an error occurs during yarn install (called as part of ghost install or ghost update) we remove the version folder for the particular install so that future runs of `ghost update` don't treat the folder as successfully installed.
> Ensure version folder is cleaned up in the event of a yarn install failure.

- lib/commands/setup.js
- lib/tasks/migrate.js
- test/unit/commands/setup-spec.js
- test/unit/tasks/migrate-spec.js
closes #708
- remove any need to save the config out of the migrations step
- instead, we set the content path during ghost setup
todo:
> fix(migrate): move setting of content-path to setup

- lib/utils/find-extensions.js
- test/unit/utils/find-extensions-spec.js
closes #723
- default to process.cwd() when folder shown by global-modules doesn't exist
> fix(extensions): fix error when global modules folder doesn't exist

- lib/commands/doctor/checks/check-permissions.js
- test/unit/commands/doctor/checks/folder-permissions-spec.js
fix(doctor): Folder permissions check considers setuid, setgid, and sticky bits
closes #724
- Prefixed the folder permissions check help command chmod parameter with "00" to clear the setuid, setgid, and sticky bits
- Updated the unit tests for folder permissions to coincide with aforementioned change
> fix(doctor): Folder permissions check considers setuid, setgid, and sticky bits

- lib/utils/update-check.js
- package.json
- test/unit/utils/update-check-spec.js
- yarn.lock
closes #675
- remove update-notifier because we weren't using most of its dependencies
- use latest-version and a simple semver check instead
> fix(update-check): swap out update-notifier for simpler check

- lib/commands/config/index.js
- test/unit/commands/config-spec.js
this is another approach to the feature added in #693 , using yargs subcommand support instead.
> feat(config): add config get & set subcommands

- lib/commands/config/index.js
- test/unit/commands/config-spec.js
closes #592
- if both url and port are passed via args, we don't want to overwrite the port of the url
> fix(config): don't overwrite url port if port is manually specified

- lib/commands/run.js
- lib/utils/local-process.js
- test/unit/commands/run-spec.js
- test/unit/utils/local-process-spec.js
closes #742
- the target process manager has not received the correct error format
I have tested production - it's different. On production we do the port polling and if Ghost does not start (because it's not a child process where we can easily receive an IPC message), we print the journalctl command to get the information why Ghost has not started.
> fix(run): local process manager forwards Ghost error message correctly

- lib/ui/index.js
- package.json
- yarn.lock
refs https://github.com/cli-table/cli-table3/issues/17
- cli-table2 is unmaintained
> chore(deps): cli-table2 => cli-table3

- lib/commands/start.js
- test/unit/commands/start-spec.js
closes #748 
The root of the problem stems from the fact we don't ensure trailing slashes when we set the URL. It's well-known that Ghost redirects URLs w/o a trailing slash to the trailing slash equivalent, so we might as well add the trailing slash here
Something that I would like to do but I'm not sure how to go about doing is add the trailing slash for existing installations. I know I can add a migration, but we also need to expect the URL will not be correct since it can be modified by running `ghost config set url https://my.site/blog`
> fix(url): ensure trailing slash gets appended to url

- lib/bootstrap.js
- lib/command.js
- lib/commands/install.js
- lib/ui/index.js
- test/unit/command-spec.js
- test/unit/commands/install-spec.js
Add ability to specify which directory Ghost should run in
refs + closes #538
WIP
- Should permissions even be checked? We already have improvements to Ghost doctor which included much more in-depth + variable permissions checks
- Tests 🙃
> feat(flags): add global `dir` option

- extensions/nginx/index.js
- extensions/nginx/test/extension-spec.js
no issue
- if you run `ghost install --no-setup` and then try to run `ghost uninstall`, the nginx extension would throw an error. This removes that error
> fix(nginx): skip uninstall if url is not set

- lib/ui/index.js
- lib/utils/update-check.js
- test/unit/ui/index-spec.js
- test/unit/utils/update-check-spec.js
- add a `clear` option to `UI.run` that will clear the output on promise resolution
- wrap update check in `ui.run` so that on slow connections something is visibly happening.
> Update check ui improvements

- extensions/systemd/index.js
- extensions/systemd/systemd.js
- extensions/systemd/test/systemd-spec.js
closes #761 
- cleanup es6 usage in systemd extension
- auto-call reset-failed when systemd is in failed state to prevent errors
> Fix issue with systemd failed state

- lib/commands/config/advanced.js
- lib/commands/config/index.js
- lib/utils/validate-instance-url.js
- test/unit/commands/config-spec.js
- test/unit/utils/validate-instance-url.js
closes #754 
I'm not sure if there should be an additional check w/ `ghost start` (it's possible to manually configure the URL so the config check wouldn't be run) - adding it would require additional checks because the admin URL could differ from the hosted URL
> fix(config): disallow URLs ending with `/ghost`

- extensions/systemd/systemd.js
- extensions/systemd/test/systemd-spec.js
- lib/commands/setup.js
- lib/commands/update.js
- lib/process-manager.js
- lib/utils/port-polling.js
- test/unit/commands/setup-spec.js
- test/unit/commands/update-spec.js
- test/unit/process-manager-spec.js
- test/unit/utils/port-polling-spec.js
refs #759
This PR is **not finished**, please no code review. Feel free to add questions or concerns  👍 
The current port polling logic to detect if a blog is up or down on start/restart is too simple and the error handling was not good, because we weren't able to receive the reason why a blog didn't start up. Using the http port to communicate with simple messages between the CLI and Ghost is impossible, because it's the http port (!). Browsers use the same transport layer.
Ghost 2.0.0 has more requirements. It executes knex-migrator internally and brings the blog into maintenance mode. That means the server starts already, but the blog is not ready or fully started.
We just change how we communicate. We don't connect to Ghost, Ghost has to connect to the CLI.
This change is backwards …
> Added handling for knex-migrator being executed in Ghost 2.0

- lib/commands/install.js
- lib/commands/update.js
- lib/utils/resolve-version.js
- test/unit/commands/install-spec.js
- test/unit/commands/update-spec.js
- test/unit/utils/resolve-version-spec.js
refs #759
- adds --v1 flag to install and update commands
- add arg to resolveVersion util that limits versions to 1.x releases
TODO:
> feat(flag): add --v1 flag to install and update

- lib/commands/update.js
- lib/utils/resolve-version.js
- lib/utils/version-from-zip.js
- test/unit/commands/update-spec.js
- test/unit/utils/resolve-version-spec.js
- test/unit/utils/version-from-zip-spec.js
refs #759
- extend version resolver
- detect major version jumps
- optimised code structure (use proper force option - this was hard to maintain/understand)
> Avoid direct upgrade to v2

- lib/commands/update.js
- lib/tasks/migrator.js
- lib/utils/resolve-version.js
- test/unit/commands/update-spec.js
- test/unit/tasks/migrator-spec.js
- test/unit/utils/resolve-version-spec.js
refs #759 
The wording won't work because I want to rebase on #772 and #771 before finalizing how the function will work
> Added confirmation/support for automatically rolling back to previous version

- lib/migrations.js
- test/unit/migrations-spec.js
closes #776
In production sites, when the ghost user is used, the content/* folder needs to be owned by the Ghost user so the ghost application will not run into permission issues. In the migration, to make sure this happens, we run the `mkdir` command using sudo (i.e. `sudo -E -u ghost mkdir {path}`). When the Ghost user isn't needed, we use the `fs-extra` library to make sure the directory exists (specifically `ensureDirSync`). `fs.ensureDirSync` is equivilant to `mkdir -p` (not `mkdir`), so the behaviour differs. By adding the `p` flag to the `mkdir` command that's run when the Ghost user is used, the behaviour between the two cases are equalized, including support for a settings folder that already exists
> Fix(migrations): allow existing content/settings folder

- lib/ui/index.js
closes #797
- say "Sudo Password" instead of "Password" to be more clear
> fix(ui): make sudo prompt more clear

- extensions/systemd/index.js
- extensions/systemd/test/extension-spec.js
- lib/commands/install.js
- lib/commands/migrate.js
- lib/commands/setup.js
- lib/commands/update.js
- lib/commands/version.js
- lib/instance.js
- lib/process-manager.js
- lib/tasks/migrator.js
- test/unit/commands/install-spec.js
- test/unit/commands/migrate-spec.js
- test/unit/commands/setup-spec.js
- test/unit/commands/update-spec.js
- test/unit/commands/version-spec.js
- test/unit/instance-spec.js
- test/unit/process-manager-spec.js
- test/unit/tasks/migrator-spec.js
refs #783
- replaces scattered usage of instance.cliConfig.x methods with standard getters/setters
todo:
> cleanup: convert cliConfig usage to get/set usage

- package.json
We use the posttest script to make linting and testing a little easier during development.
Aside: it would be great to also get this repo using `yarn ship` to do a full release. @AileenCGN I think you have some docs somewhere for the release process?
----
- This little trick makes testing easier, as linting runs last
- Don't really care about linting til the tests pass!
- Standardised with other Ghost repos :)
> 🛠  Moved yarn lint to posttest

- package.json
- yarn.lock
- includes lockfile regeneration
- was held back for manual testing
The major breaking changes don't seem to impact the CLI, although I haven't tested a full `ghost install` with arguments
> chore(deps): upgrade yargs to 12.0.1

- yarn.lock
no issue
- yarn 1.10 adds the integrity field
- normalizing resolved link
> chore(deps): regenerate yarn.lock file

- lib/utils/pre-checks.js
- test/unit/utils/pre-checks-spec.js
closes #834
- add fs.existsSync check to task `enabled` fn
> fix(pre-check): don't run config check if folder doesn't exist

- package.json
no issue
- see https://nodejs.org/en/blog/release/v10.13.0/
@acburdine This needs a new release. If this is released in the CLI, we can release https://github.com/TryGhost/Ghost/pull/10125.
> Bumped Node v10 min version

- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/--anything-else.md
- README.md
- lib/commands/start.js
- lib/commands/update.js
- lib/tasks/major-update/ui.js
- lib/tasks/migrator.js
no issue
- update old docs links
@ErisDS @kirrg001 I had to guess at some of the link replacements, as the original docs for some of the troubleshooting things weren't available.
> chore(docs): update links to new docs site

- lib/tasks/yarn-install.js
- lib/utils/resolve-version.js
- package.json
- test/unit/tasks/yarn-install-spec.js
- test/unit/utils/resolve-version-spec.js
- yarn.lock
While investigating/testing the update notification stuff for prerelease versions, I realized that the `package-json` package exists and that we already depend on it through the `latest-version` package. 
This PR removes some of the places where we were shelling out to the `yarn` command in favor of simply calling the `package-json` module. Simplifies the code and probably improves perf a bit due to not having to spin up yarn each time.
TODO:
> feat(yarn): use package-json instead of yarn for version resolution

- lib/commands/install.js
- lib/utils/dir-is-empty.js
- test/unit/commands/install-spec.js
- test/unit/utils/dir-is-empty.js
closes #868
- add dir-is-empty util that checks empty directories correctly
TODO:
> fix(install): ignore dotfiles except for .ghost-cli in dir check

- extensions/nginx/templates/nginx-ssl.conf
- extensions/nginx/templates/nginx.conf
closes #843
- add comment about acme.sh requirement
doesn't really need a migration imo since it's only a documentation update
> docs(nginx): add note to conf file about acme.sh root

- lib/utils/pre-checks.js
- test/unit/utils/pre-checks-spec.js
closes #867
- add GHOST_CLI_PRE_CHECKS environment variable that can be
set to 'false' to skip pre checks
> feat(pre-checks): add ability to skip pre-checks with env var

- lib/bootstrap.js
- lib/commands/install.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/commands/update.js
- test/unit/commands/install-spec.js
Whilst attempting to update our CLI docs, I found lots of places where the CLI output was very hard to read. We have a LOT of flags, so it can become really really tricky to understand what is / isn't possible when reading the help output.
Help should be the source of truth, so I've updated it to be a little clearer. None of these changes should be functional, except the expansion to having `--version1` as the long form of `--v1`.
Everything else should _only_ affect what help outputs.
The main thing is that global options are now shown in a "global options" group. The only options left in `Options:` are the command specific options. I've also tweaked the order, so that the commands are easier to read. 
---
A side note: in Gscan and other cli-based tools we use …
> Improve the CLI help output

- lib/commands/check-update.js
- test/unit/commands/check-update-spec.js
closes #876
- add check-update command to check for available updates
> feat: add check-update command

- lib/system.js
- test/unit/system-spec.js
refs #936
- check if name matches global config name as well
The problem (I think) is that if you delete the contents of a ghost install directory without running `ghost uninstall`, the entry in `~/.ghost/config` never gets removed, and thus if you attempt to install Ghost in the _same_ directory again, the hasInstance check would happily report that the instance had already been set up. This expands the check to _also_ check the name field.
Note: upon further thought this may only fix half of the issue - may need a follow-up PR to expand the check in the `isSetup` getter in the instance class.
> fix(system): improve hasInstance check

- extensions/nginx/acme.js
- extensions/nginx/index.js
- lib/commands/doctor/checks/system-stack.js
no issue
- Respect environment variables that customise where nginx lives and what it is called
- Use env vars, not config, because this will be system-wide
- Allows CLI to work with "flavours" of nginx, like OpenResty
The two env vars are:
NGINX_PROGRAM_NAME
NGINX_CONFIG_PATH
I did wonder as part of this if `dpkg -l | grep xxx` is the best way to find out if something is installed, and whether using which, or a version check, might be more interoperable 🤔 (thinking about the case of symlinking openresty as nginx)
> feat(nginx): customisable paths & program name

- lib/bootstrap.js
- lib/command.js
- lib/errors.js
- lib/extension.js
- lib/instance.js
- lib/migrations.js
- lib/process-manager.js
- lib/system.js
- test/unit/command-spec.js
this PR can only be merged once we're ready to drop support for node 6 in the CLI (it will also fail tests until that point too). It adds async/await usage to the base classes (aka files in the root of `lib/`) and fixes tests (primarily command-spec which was relying on inconsistent promise return values)
> refactor(base): use async/await in base classes

- lib/tasks/migrator.js
- test/unit/tasks/migrator-spec.js
refs https://github.com/TryGhost/knex-migrator/pull/175
- detect if an irreversible migration error was thrown when performing a rollback and output a useful error message
> Added error handling for irreversible migrations

- lib/utils/version.js
When testing installs with a prerelease version of the CLI the satisfy check against Ghosts engines field in package.json fails.
> fix(utils): prerelease should statisfy engine requirements

- extensions/systemd/systemd.js
Expecting to fix #805, @kirrg001 please provide any feedback. I also thought in adding this line inside a `.then()` once the `systemctl stop ${this.systemdName}` had run, what do you think?
> [Enhancement] Delete bootstrap-socket once ghost is stopped

- lib/commands/config.js
closes #981
- this enables the config command to be run as the root user
> fix(config): allow root user to run config command

- lib/tasks/yarn-install.js
- test/unit/tasks/yarn-install-spec.js
@acburdine Can we add a tiny little fix like this and ship it to help with debugging https://github.com/TryGhost/Ghost/issues/11129?
I'm not sure if we also need to fix https://github.com/TryGhost/Ghost-CLI/blob/master/lib/utils/yarn.js to include stderr as mentioned in https://github.com/lovell/sharp/issues/1942#issuecomment-547513885 but that all seems like it needs a bit more time and attention. 
Definitely want to switch to outputting this info to a log file as well, but again, that takes time whereas this could help immediately.
> Added verbose yarn output

- lib/tasks/migrator.js
- test/unit/tasks/migrator-spec.js
refs #978
- ProcessError will correctly respect the stderr property passed to it
> fix(migrator): use ProcessError instead of GhostError

- lib/commands/start.js
- lib/commands/stop.js
- lib/instance.js
- lib/process-manager.js
- test/unit/commands/start-spec.js
- test/unit/commands/stop-spec.js
- test/unit/instance-spec.js
- test/unit/process-manager-spec.js
refs #783
- move start/stop functionality into instance class
- add base stub methods for ProcessManager
- refactor stop/start commands to use new instance functionality
> refactor(instance): move start/stop logic into instance class

- lib/tasks/import/api.js
- test/unit/tasks/import/api-spec.js
no issue
- return more accurate error messages for authentication errors
> fix(import): improve handling of auth errors

- .travis.yml
- package.json
- node v8 became EOL on December 31st
> feat(node): drop node v8 support

- lib/commands/install.js
- lib/commands/update.js
- test/unit/commands/install-spec.js
fixes the `ghost install 2` case throwing an error
> fix(version): ensure custom version is handled as a string

- lib/tasks/major-update/ui.js
- test/unit/tasks/major-update/ui-spec.js
allows for automatic major version upgrades, assuming the theme has no warnings or errors.
> fix(major): allow automatic major upgrades for clean themes

- lib/command.js
- test/unit/command-spec.js
refs #1140, #793 
when `process.exit()` is called, it doesn't fire a SIGINT or SIGTERM event, it fires an `exit` event. Adding an event listener for process.exit should fix some cases of cleanup not being called
> fix(cleanup): ensure cleanup gets run on process.exit calls

- lib/command.js
- lib/utils/check-valid-install.js
- lib/utils/find-valid-install.js
- test/unit/command-spec.js
- test/unit/utils/check-valid-install-spec.js
refs #800 
- Try to go up the directory tree to find a valid Ghost instance
- Can be disabled with global config ('traverse_dirs')
- We need to determine if there's a better way of doing this, or how global config should work in general
- I was thinking of adding a migration which prompts the user, but that feels overkill
- I want to get a code review before I write the tests 😄
> feat(instance): traverse up directory tree to find instance

- lib/migrations.js
- lib/tasks/configure/options.js
- test/unit/migrations-spec.js
- test/unit/tasks/configure/options-spec.js
- ensure dbpath argument is absolute by default
- add migration to make relative sqlite paths absolute
NOTE: depends on functionality from #1210
> feat(sqlite): ensure sqlite db path is absolute

- lib/commands/install.js
- test/unit/commands/install-spec.js
closes https://github.com/TryGhost/Ghost-CLI/issues/1218
> fix(install): rename force flag to 'check-empty'

- lib/commands/update.js
- test/unit/commands/update-spec.js
refs https://github.com/TryGhost/Ghost-CLI/issues/201
> feat(update): reduce number of kept versions to 2

- lib/commands/log.js
- test/unit/commands/log-spec.js
Originally discovered on [the forum](https://forum.ghost.org/t/migration-from-wordpress-to-ghost-hosted-by-digital-ocean-droplet-fails/17434)
> fix(log) prevent error when no transports exist

- extensions/mysql/index.js
- extensions/mysql/test/extension-spec.js
refs #1265
- refactor mysql extension to use async/await
- add separate setup steps for MySQL 8
> feat(mysql): support MySQL version 8

- extensions/systemd/index.js
- extensions/systemd/test/extension-spec.js
- lib/commands/setup.js
- lib/extension.js
- lib/ui/index.js
refs #308, #1115
I'm not sure if this is the best way to do this, but it's the most pluggable thing that came to mind. I haven't fully tested this or ensured that changing the process manager the way I did will actually work 😄 It's best to look at 28a85b8 individually since it's the only logical change.
@acburdine can you please take a cursory look at this?
> feat(extensions): add `user skipped` task hook

- lib/extension.js
- test/unit/extension-spec.js
The idea behind this PR is to rethink how we're handling the generation of configuration files for things like nginx + systemd. Currently, the configuration files are stored inside the Ghost site's installation directory and symlinked into the proper directory on the system, but this has come with a few drawbacks, and does not in hindsight provide that much of a benefit.
If a person wants to modify their configuration files after Ghost-CLI generates them, then they can visit the directories on the system that those files normally reside in (i.e. `/etc/nginx` for nginx) and edit them there.
As a side benefit, this removes the one significant complication that would prevent us from converting our usage of `inquirer` to `enquirer`.
> feat(extension): rewrite template method

- lib/commands/install.js
- lib/utils/version.js
- test/unit/commands/install-spec.js
- test/unit/utils/version-spec.js
this will allow Ghost maintainers to "deprecate" a Ghost version if it contains known severe bugs. A deprecated version will not be installable unless someone specifies the version exactly, and provides the `--force` flag.
> feat(version): add handling for deprecated Ghost versions

- lib/commands/update.js
- lib/tasks/release-notes.js
- test/unit/commands/update-spec.js
closes https://github.com/TryGhost/Ghost-CLI/issues/1338
- we want to be able to display the release notes so we can inform users
about new features
> feat(update): display release notes when updating Ghost

- lib/commands/config.js
I've seen a lot of cases in the forum where users make config changes but don't restart Ghost. This PR reminds the user to restart Ghost (if it's running) after making a configuration change.
Will need a copy review 😄
> feat(config): remind user to restart ghost after making changes

- lib/commands/log.js
- lib/commands/stop.js
In #820 we added support for traversing the directory tree to find a Ghost instance. It turns out both `stop` and `log` haven't supported this, so this PR fixes that.
Note that `doctor` also uses the `findValidInstall` util, but I'd like to get a second set of eyes before enabling directory traversal in it.
> chore(log,stop): enable directory traversal

- .github/workflows/e2e-test.yml
previously, we had to install Nginx on the action runner in order to run e2e tests. Upon installation, apt-get would automatically start the Nginx service.
Since nginx is already installed, no such automatic start occurs and we have to start it in the test scripts
> ci: ensure nginx service is started

- lib/commands/install.js
- lib/commands/update.js
- lib/instance.js
- lib/utils/version.js
- test/unit/commands/install-spec.js
- test/unit/commands/update-spec.js
- test/unit/utils/version-spec.js
this adds a new `--channel` flag to the install command that will allow installing prereleases for local installs if desired.
> feat(channel): add ability to specify release channel for local installs

- lib/utils/version.js
- test/unit/utils/version-spec.js
no issue
- previously, the supported version policy was you could update to any new major if you were on the latest v1
- now, we're expanding that to say you can upgrade to any new major only if you're on the latest version of the current major
> feat(version): expand v1 update policy to cover all versions

- .github/workflows/local-e2e-test.yml
- lib/commands/run.js
- test/unit/commands/run-spec.js
no issue:
- Ghost in v4+ emits two events on successful start: 'started' and 'ready', so we need to handle both
- The error message structure in v4 events also changes, so we need to handle things there as well
> feat(local): handle v4 boot events in local process manager

- lib/process-manager.js
- lib/utils/port-polling.js
- test/unit/process-manager-spec.js
- test/unit/utils/port-polling-spec.js
no issue
- handles separate 'ready' event from Ghost v4+
> feat(boot): handle v4 boot events in port-polling util

- lib/utils/version.js
- test/unit/utils/version-spec.js
no issue
- if one of the versions in a comparison is a prerelease (i.e. comparing
v3.0.0 and v4.0.0-alpha.1), semver.diff returns 'premajor' instead of
'major', so we need to handle both cases.
> fix(version): add premajor to update version diff check

- .github/workflows/stale.yml
no issue
- we want a workflow to automatically mark old issues and PRs as stale
- this commit does the following:
* adds comment messages for both stale issues and PRs
* sets the number of days before we mark as stale to a very generous
time of 120 days
* adds the `feature` and `pinned` labels to the exemptions list
- all of this will run at 00:30
> ci: added `@actions/stale` workflow to manage issues and PRs

- packages/ghost-cli/lib/tasks/yarn-install.js
- packages/ghost-cli/test/unit/tasks/yarn-install-spec.js
This has been reported a few times on the forum, but the most recent is 
https://forum.ghost.org/t/ghost-v4-9-4-is-not-compatible-with-the-current-node-version/24160
Adds the required node/cli ranges to the error message for better context
> chore(docs): improve error message when node or cli version is incompatible

- .github/workflows/e2e-test.yml
- this is no longer supported by GitHub and will no longer run
> ci: remove eol ubuntu-16 test runner from matrix

- packages/ghost-cli/lib/migrations.js
- packages/ghost-cli/lib/tasks/ensure-structure.js
- packages/ghost-cli/test/unit/migrations-spec.js
- Recently we've added 3 new folders to content in Ghost: media, files and public
- This updates Ghost-CLI to create the folders for both new and existing installs
This is not urgent, but the migration before version will need updating in line with whenever this gets released, I think. Not sure I understood how that works.
> Added 3 new folders to content

- lib/migrations.js
- lib/tasks/ensure-structure.js
- test/unit/migrations-spec.js
- Recently we've added 3 new folders to content in Ghost: media, files and public
- This updates Ghost-CLI to create the folders for both new and existing installs
> feat: add 3 new folders to content directory (1.x backport)

- lib/utils/version.js
- test/unit/utils/version-spec.js
refs https://github.com/TryGhost/Toolbox/issues/157
- we've had several bugs in Ghost where users would like to go back to a
previous version, but `ghost update <version>` doesn't let them go
back to a version smaller than their current version
- `ghost update <version> --rollback` doesn't work for certain users if
they've freshly installed Ghost
- by handling `--force`, we can let users choose to go back to an
arbitrary version at their own discretion
- also adds a test to ensure `force` works with the util
> fix(version): handled force flag when specifying versions

- .github/workflows/local-e2e-test.yml
- lib/tasks/yarn-install.js
- test/unit/tasks/yarn-install-spec.js
closes #1590, #1591
Yarn 1.x is the launching point for users to get yarn >2. When a user runs `yarn set version berry`, a .yarnrc.yml will be created in their home directory with the path to yarn >2:
```bash
$ cat ~/.yarnrc.yml
yarnPath: .yarn/releases/yarn-3.1.1.cjs
```
The YARN_IGNORE_PATH environment variable prevents the `yarnPath` from being used, but still allows other options in the yarnrc locations to be picked up (e.g. registry).
Here's the bootstrapping logic in yarn:
https://github.com/yarnpkg/yarn/blob/728feb1414cec2d5cb8ecf8c061bc10f03b99def/src/cli/index.js#L625-L627
And here's a search for YARN_IGNORE_PATH in the repo, suggesting this _shouldn't_ have a negative impact
https://github.com/yarnpkg/yarn/search?q=YARN_IGNORE_PATH
/cc @Paladiamors can you try this patch and …
> fix(yarn): use bundled yarn version

- extensions/mysql/index.js
- extensions/mysql/test/extension-spec.js
- package.json
- yarn.lock
refs https://github.com/TryGhost/Toolbox/issues/174
- this commit lays the groundwork for full support of MySQL 8 by
switching Ghost-CLI to using `mysql2`, which supports MySQL's
`caching_sha2_password` authentication method
> chore(deps): switched from `mysql` to `mysql2`

- extensions/mysql/index.js
- extensions/mysql/test/extension-spec.js
- lib/utils/deprecation-checks.js
refs https://github.com/TryGhost/Toolbox/issues/176
- we're going to be making some changes to the list of supported databases in
Ghost 5.0 so we need to start informing self-hosters if their DB is
due to become unsupported
- specifically, SQLite will only be supported in development mode, and
MySQL 5.7 will not going to be supported at all
- this commit adds a deprecation check to CLI that adds a warning when
we encounter a database that is due to be unsupported in coming months
> feat(deprecation): added notice when using a deprecated database

- extensions/nginx/index.js
You have a number of people reporting that nginx is not detected in their environment, and a couple people reporting it's because the service name evaluates to something like'  nginx'. This uses std lib trim() functionality to remove the whitespace. Tested on an Ubuntu system that was not working before this fix and is now working after.
> trim whitespace from service names

- extensions/nginx/templates/nginx-ssl.conf
This request implements the recommendation in https://github.com/TryGhost/Ghost-CLI/issues/1661
However, I've done some more follow-up research that leaves me uncertain on whether to recommend merging this.
In the linked issue, I recommended allowing unlimited upload size, but scoped to a route that only works for admins. That's a sound idea, but it only works to block unwanted large uploads if authentication happens before all that data is sent.  So I put together a test:
I submitted an upload to admin-only endpoint as an unauthenticated user, sending a file that was larger than `client_max_body_size`. So my request has two reasons to fail: It's not authenticated and it's too big. The question is: which problem will problem trigger first? 
In my tests, the `client_max_body_size` limit …
> feat(nginx): Trust admins to upload large files

- .github/workflows/e2e-test.yml
- .github/workflows/local-e2e-test.yml
- removed Ubuntu 18 as it is EOL on GHA
- switched from Node 14 to 16 as this is our recommended version
- removed the MySQL password workaround because Ghost-CLI should support all auth types now
> Updated E2E CI testing workflows

- lib/commands/doctor/index.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/utils/get-instance.js
- test/unit/commands/doctor/command-spec.js
- test/unit/commands/setup-spec.js
- test/unit/commands/start-spec.js
- test/unit/commands/stop-spec.js
- test/unit/utils/get-instance-spec.js
Adds functionality similar to the stop command - `ghost start {name}` now works as `ghost stop {name}` always has
I realized this wasn't a thing as I was testing #765, and given the Stop command already has this functionality, I figured it would be a 5 minute fix, but it turns out both the Start and Stop Command Unit tests aren't super dry, so I ended up going down the rabbit hole of drying up the tests. It might be easier to review commit by commit 😬 
I know this coincides w/ the release of 1.9.0; I don't think it will make much of a difference if this gets released before or afterwards.
> feat: added support for named start

- lib/commands/run.js
- lib/errors.js
- Ghost errors contain context messages that were not being output
- These messages often have the most important information in them
- Updated Ghost CLI to show this if present
> fix(errors): Show full Ghost Error message output

- extensions/nginx/templates/nginx-ssl.conf
- extensions/nginx/templates/nginx.conf
refs: https://github.com/orgs/TryGhost/projects/57/views/21
X-Forwarded-For is used to determine the client IP address within Ghost, and is used in some rate-limiting scenarios. The original setting for this was to use Nginx's $proxy_add_x_forwarded_for variable, which appends to the list.
Since it's trivial to spoof a client address with this mode, the default case should be to assume this is the most external proxy (i.e. this Nginx server is what clients connect to, with no other proxies in-between).
If someone has a setup which uses a CDN or additional reverse proxies, then this configuration will need changing to use $proxy_add_x_forwarded_for, and additional configuration may be required to ensure that only the next proxy in the chain can access Nginx.
> Ensure X-Forwarded-For is correct in default case

- lib/tasks/import/api.js
refs https://github.com/TryGhost/Product/issues/3578
- The export API, by default is limited to 15 members.
- This sets the API endpoint to query all members via the CLI.
> 🐛 Fixed not all members being exported in CLI

- .github/workflows/local-e2e-test.yml
no issue
- local e2e tests were failing on macos because of improper usage of the `sleep` command
- on macos, the `sleep` command doesn't accept a suffix (e.g. 's', 'm', 'h'), only an integer which by default is in seconds
> Fixed sleep command in CI local-e2e test workflow

- lib/commands/install.js
- lib/commands/update.js
- lib/tasks/backup.js
- test/unit/commands/install-spec.js
- test/unit/commands/update-spec.js
refs TryGhost/Product#3510
- Until now, Ghost has always shipped with a single built-in theme, Casper. This change adds support for Ghost to ship with multiple built-in themes.
- Updated the install and update commands to create symlinks for any theme that is shipped alongside Ghost (e.g. any theme in `ghost/core/content/themes`)
- When rolling back with `ghost update --rollback`, any symlinks that are broken in the process will be removed
> ✨ Added support for multiple built-in themes

- extensions/nginx/templates/nginx-ssl.conf
- extensions/nginx/templates/nginx.conf
- extensions/nginx/templates/ssl-params.conf
ref https://linear.app/tryghost/issue/ONC-179
- self-hosters reported seing a prompt to download "auth-frame" when visiting a post with comments enabled on iOS
- recently, we've worked on an optimisation for comments UI to return a empty 204 for `/ghost/auth-frame/` when no staff admin is authenticated (more context: https://github.com/TryGhost/Ghost/pull/19840)
- setting `X-Content-Type-Options` to `nosniff` helps to prevent browsers from interpreting files as a different MIME type than what is specified in the `Content-Type` header
- however, when returning an empty 204 response (`No Content`, therefore no `Content-Type` to check), iOS safari interprets the header as a file to download for some reason
- with this change, we add the `nosniff` header to only non-empty responses (i.e. not …
> Updated nosniff header to apply to non-204 responses only

- lib/command.js
- test/unit/command-spec.js
reported on the [forum](https://forum.ghost.org/t/ghost-run-d-throws-typeerror/42487)
depends on https://github.com/TryGhost/Ghost-CLI/pull/1814
> 🎨 add warning when `-d` is provided instead of `-D`

- lib/tasks/yarn-install.js
- lib/utils/version.js
closes #1899
- at some point the syntax changed, so we need to pass the agent differently
> fix(install): pass agent correctly to packageJson function

- .github/workflows/local-e2e-test.yml
refs https://github.com/TryGhost/Ghost-CLI/actions/runs/12701391399/job/35405814839
- we have a random failure that I can't figure out and is blocking `main` from being green
- given Windows is not an officially supported platform, we can just disable it for now to unblock shipping and then come back to this in the future
> Disabled local Windows E2E test due to random failure

- lib/tasks/import/tasks.js
- test/unit/tasks/import/tasks-spec.js
refs #1952
- add support for GHOST_CLI_STAFF_AUTH_TOKEN env var to remove the need for prompting in automated backup scenarios
> feat(backup): support specifying backup staff token via env var

- lib/tasks/configure/options.js
- test/unit/tasks/configure/options-spec.js
closes #1968
- add mailgun to list of allowed mail transports
While not officially documented, it does appear to be supported here: https://github.com/TryGhost/framework/blob/main/packages/nodemailer/lib/nodemailer.js#L40-L49 so we're adding it to avoid unnecessary errors when running `ghost doctor`.
> fix(config): allow mailgun as valid transport
