- .gitignore
> improve gitignore to ignore editor generated files

- bin/ghost
- lib/utils/update-notifier.js
- package.json
> display update notifications when a newer ghost cli is available

- lib/utils/npm.js
- test/unit/utils/npm-spec.js
no issue
This exists to ensure coveralls works for PRs
> :white_check_mark: Add tests for npm utility

- lib/commands/config/advanced.js
- lib/commands/config/index.js
Can use ghost config --url <value> as parameter.
> Add url as parameter

- lib/commands/config/advanced.js
- lib/commands/config/index.js
- test/acceptance/config-spec.js
refs #64
- remove pg from allowed database types
- improve config prompts & prompt for mysql connection parameters
> Add prompts for mysql database information

- lib/commands/config/advanced.js
- lib/commands/run.js
- lib/commands/setup.js
- lib/process/index.js
- lib/process/local.js
- lib/process/systemd/ghost.service.template
- lib/process/systemd/index.js
> Add systemd process manager

- lib/commands/update.js
closes #168
- fix the regression introduced by the es6 update
> fix(update): fix update command when install folder already exists

- lib/commands/config/advanced.js
- lib/commands/doctor/checks/startup.js
- lib/commands/start.js
- lib/errors.js
closes #26
- add `startup` checks to ghost-cli
> feat(startup): validate config on startup

- lib/commands/ls.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/stop.js
closes #178
- remove register/deregister from ghost start/stop
- change system config file structure and pull url/port/process manager data from individual
instance configs rather than a global list
> feat(ls): show stopped ghost instances as well as running ones

- lib/commands/log.js
- lib/commands/ls.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/stop.js
no issue
- fixes `ghost log` command broken by previous changes
- simplifies `ghost ls` a bit
> fix(ls): store running environment in system config

- lib/services/nginx/index.js
- lib/services/process/systemd/index.js
- lib/ui.js
closes #164
- add sudo ui method that shows the sudo command before it is run
- make log method synchronous again
> feat(ui): show sudo command before it is run

- lib/command.js
- lib/commands/doctor/checks/setup.js
- lib/commands/doctor/index.js
- lib/commands/install.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/update.js
- lib/tasks/yarn-install.js
- lib/ui/index.js
- lib/ui/renderer.js
closes #181
- add custom Listr renderer that works better with other UI methods e.g. log, prompt, run
- refactor commands to use this.ui.listr instead of new Listr()
- fix various command arg bugs
> feat(ui): add custom listr renderer and move listr to ui class

- extensions/systemd/systemd.js
- lib/instance.js
- lib/process-manager.js
- lib/utils/local-process.js
- package.json
- yarn.lock
closes #207
- updates the running check to make sure the process is actually running
- adds a method to the process manager class (required to implement)
> feat(process): update running check to call process manager

- extensions/nginx/commands/ssl-renew.js
- extensions/nginx/index.js
- extensions/nginx/letsencrypt.js
- lib/commands/setup.js
- package.json
- yarn.lock
Two things in this PR:
- feat(nginx): check dns points to ip before attempting ssl setup
refs #190
- adds check to ssl setup that ensures DNS has been properly configured before trying to get an SSL certificate
- ssl renew command for nginx extension
TODOS
> Nginx Improvements

- extensions/systemd/systemd.js
closes #262
- add precheck to all systemd commands todetermine whether or not systemd is set up before running
> fix(systemd): ensure systemd service file is created before starting

- lib/commands/doctor/checks/setup.js
closes #260
- fixes error handling to be actually fixed this time
> fix(doctor): actually fix stack check errors

- extensions/nginx/index.js
closes #283
- cleanup promise handling in ssl setup
> fix(ssl): ensure ssl setup works using the --sslemail flag

- extensions/mysql/index.js
- extensions/mysql/package.json
- lib/commands/config/index.js
- lib/commands/doctor/checks/startup.js
- lib/commands/log.js
- lib/errors.js
- lib/tasks/migrate.js
- lib/ui/index.js
- test/unit/tasks/migrate-spec.js
- test/unit/ui/index-spec.js
> general config/ui/mysql cleanup

- extensions/linux/index.js
- lib/commands/uninstall.js
no issue
- with the permissions change in #296, the ownership of the ghost directory was changed. Because of this we need to sudo remove the directory on uninstall
> fix(uninstall): ensure uninstall succeeds if using ghost user

- extensions/systemd/index.js
closes #293
- reload systemd daemon on template generation to persist any file changes
> fix(systemd): ensure systemd daemon is reloaded

- lib/commands/log.js
> fix(log): don't error out if the log file doesn't exist

- extensions/linux/index.js
- extensions/mysql/index.js
- extensions/nginx/commands/ssl-renew.js
- extensions/nginx/index.js
- extensions/systemd/index.js
- lib/command.js
- lib/commands/doctor/checks/install.js
- lib/commands/install.js
- lib/commands/log.js
- lib/commands/ls.js
- lib/commands/restart.js
- lib/commands/run.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/commands/uninstall.js
- lib/commands/update.js
- lib/commands/version.js
All of the changes in this PR should only be changing text output
refs #313
- Text-Only changes, no logic has been updated
- use correct capitalisation for various product names
- updates for consistency
- various other tweaks
> 💄 🐷  fix(ui): various text-only tweaks

- extensions/linux/index.js
- extensions/mysql/index.js
- extensions/nginx/index.js
- extensions/systemd/index.js
- lib/commands/doctor/checks/install.js
- lib/commands/setup.js
Second pass at text-only changes.
Will get to the functional ones now.
refs #313
- always use stage description, not name
- update stage descriptions
- update title of nginx & systemd checks & make MySQL check consistent
> 💄 🐷 fix(ui): tweak task output for setup stages

- extensions/nginx/index.js
closes #331
- fix skip logic in ssl tasks
cc @ErisDS -> I didn't see a PR for the issue yet so went ahead and created one.
> fix(ssl): actually skip ssl generation tasks if dns check fails

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- README.md
cc @ErisDS @JohnONolan for a review of wording
> Update some docs

- extensions/nginx/index.js
no issue
- fixes ssl setup issue
> fix(ssl): ensure well-known block actually gets created

- lib/bootstrap.js
- lib/command.js
- test/unit/command-spec.js
Raising this just to flag up that I have a handful of very minor text-based tweaks I'd like to make.
These are mostly dependent on docs urls, so need to finish updating docs a bit first.
In this PR so far I have swapped around the checks for pre 1.0.0 and dev installs - I haven't tested this, but short term it seems like pre 1.0.0 is more likely, and so should be the first message.
I'm also adding a link to the migration guide
> More text-based tweaks 😁

- lib/commands/setup.js
V2 - maybe less controversial 😬
> fix(help): explicit setup stages

- lib/command.js
- lib/commands/buster.js
- lib/commands/config/index.js
- lib/commands/doctor/index.js
- lib/commands/install.js
- lib/commands/log.js
- lib/commands/setup.js
- test/unit/command-spec.js
- fix(help): add onlyOptions argument to configureOptions
> Fix command help output

- lib/commands/config/advanced.js
- lib/commands/config/index.js
@austin - I couldn't get `coerce` to work, no matter _where_ I put it! Dunno if you can find a more elegant solution for this?
closes #399
- I tried to do this with the yargs coerce method but couldn't find anywhere that it worked
- Instead, have implemented a transform method and added toLowerCase for urls
> fix(config): transform urls to lowercase

- bin/ghost
> fix(run): disable update check on `ghost run`

- lib/commands/setup.js
> fix(setup): add linux-user step to be skipped with flag

- lib/commands/doctor/checks/install.js
- package.json
- test/unit/commands/doctor/install-spec.js
closes #410
- throw errors instead if prompts are disabled
- fix error if remote mysql host is used
TODO: tests
> fix(doctor): fix prompting and error handling with --no-prompt

- lib/tasks/migrate.js
- test/unit/tasks/migrate-spec.js
refs #281 
cc @ErisDS for wording
> Improve sqlite error message

- lib/command.js
- lib/commands/config/advanced.js
- lib/errors.js
- test/unit/command-spec.js
- test/unit/commands/config-spec.js
- test/unit/errors-spec.js
- test/unit/extension-spec.js
- test/unit/system-spec.js
Working towards getting better test coverage across the CLI.
> 🍀 write tests every day 🍀

- extensions/mysql/test/extension-spec.js
- extensions/nginx/test/extension-spec.js
- extensions/systemd/test/extension-spec.js
- extensions/systemd/test/get-uid-spec.js
- extensions/systemd/test/systemd-spec.js
- package.json
- test/unit/commands/buster-spec.js
- test/unit/commands/doctor/command-spec.js
- test/unit/commands/doctor/startup-spec.js
- test/unit/commands/install-spec.js
- test/unit/commands/log-spec.js
- test/unit/commands/ls-spec.js
- test/unit/commands/run-spec.js
- test/unit/commands/setup-spec.js
- test/unit/commands/start-spec.js
- test/unit/commands/stop-spec.js
- test/unit/commands/uninstall-spec.js
- test/unit/commands/update-spec.js
- test/unit/commands/version-spec.js
- test/unit/tasks/ensure-structure-spec.js
- test/unit/tasks/linux-spec.js
- test/unit/tasks/yarn-install-spec.js
- test/unit/ui/renderer-spec.js
- test/unit/utils/find-extensions-spec.js
- this gives us a more accurate representation of what the repo test coverage actually is 🙈
- include extension tests in test run
> chore(test): add test stubs for remainder of files

- lib/commands/buster.js
- lib/commands/config/index.js
- lib/commands/install.js
- lib/commands/log.js
- lib/commands/ls.js
- lib/commands/run.js
- lib/commands/setup.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/commands/uninstall.js
- lib/commands/update.js
- lib/commands/version.js
refs #428
- defer requiring modules in commands to as late as possible
> perf: lazily require modules in commands

- extensions/systemd/get-uid.js
- extensions/systemd/index.js
- extensions/systemd/systemd.js
- extensions/systemd/test/extension-spec.js
- extensions/systemd/test/get-uid-spec.js
> Improve Systemd checks

- lib/tasks/linux.js
- lib/tasks/yarn-install.js
- test/unit/commands/buster-spec.js
- test/unit/commands/ls-spec.js
- test/unit/commands/run-spec.js
- test/unit/commands/version-spec.js
- test/unit/tasks/ensure-structure-spec.js
- test/unit/tasks/linux-spec.js
- test/unit/tasks/yarn-install-spec.js
- test/utils/config-stub.js
no issue
- improve test coverage
> add more tests

- extensions/mysql/index.js
- extensions/mysql/test/.eslintrc.json
- extensions/mysql/test/extension-spec.js
- extensions/nginx/index.js
- extensions/nginx/test/.eslintrc.json
- extensions/systemd/get-uid.js
- extensions/systemd/index.js
- extensions/systemd/systemd.js
- extensions/systemd/test/.eslintrc.json
- extensions/systemd/test/extension-spec.js
- extensions/systemd/test/get-uid-spec.js
- package.json
no issues
- linting wasn't being run on the extensions directory, this enables linting on that directory and fixes any lint issues
> chore(lint): ensure extensions are linted, fix lint issues

- lib/system.js
- test/unit/system-spec.js
no issue
- allows commands that call extension hooks to use the returned hook result
> fix(system): use mapSeries rather than each

- test/unit/ui/index-spec.js
- test/unit/ui/renderer-spec.js
Adding tests related to UI - the module and the renderer
I tried to have the order of tests match the order of creation in the file
> Add UI tests

- package.json
- yarn.lock
Not sure if it's useful to PR this, but I just did a fresh release to add a new error code for when things have gone really wrong 😁  See TryGhost/knex-migrator#76 for context.
> chore(deps): knex-migrator@2.1.7

- extensions/nginx/index.js
- extensions/nginx/templates/ssl-params.conf
closes #487
- put dhparam.pem and ssl-param.conf in nginx snippets directory
> feat(ssl): only generate dhparam and ssl-params once per server

- lib/ui/index.js
- lib/utils/config.js
- lib/utils/local-process.js
- lib/utils/yarn.js
no issue
- not super important, but removes an unnecessary require
> chore: remove lodash/assign usage in favor of Object.assign

- extensions/nginx/index.js
- lib/tasks/migrate.js
- lib/ui/index.js
- test/unit/ui/index-spec.js
no issue
- improve ui flow by allowing spinner to run during sudo command
- ui listens on stderr and prompts for password if sudo does
TODO:
> fix(ui): improve sudo output suppression

- extensions/nginx/index.js
this _should_ in theory fix our acme.sh issues, although it needs testing on ubuntu to confirm.
Will test tomorrow to make sure it's working correctly, then merge + release :)
> acme.sh usage fixes

- extensions/nginx/test/extension-spec.js
- package.json
Adds tests related to the nginx extension - coverage hits 100% 😄
> chore(tests): Add Nginx unit tests

- extensions/nginx/index.js
- extensions/nginx/test/extension-spec.js
- package.json
closes #524 - removes the undocumented requirement for git to be installed system-wide for the CLI to work.
> chore(deps): remove git dependency as requirement

- bin/ghost
- lib/utils/update-check.js
- lib/utils/update-notifier.js
- test/unit/utils/update-check-spec.js
closes #525
- make update check more prominent
TODO: add tests
> feat(ui): improve update notifications

- lib/commands/uninstall.js
> Update uninstall wording to say folder contents will be deleted

- extensions/nginx/acme.js
- extensions/nginx/index.js
- extensions/nginx/migrations.js
- extensions/nginx/test/acme-spec.js
- extensions/nginx/test/extension-spec.js
- extensions/nginx/test/migrations-spec.js
- lib/commands/migrate.js
- lib/commands/update.js
- lib/migrations.js
- lib/utils/needed-migrations.js
- package.json
- test/unit/commands/migrate-spec.js
- test/unit/commands/update-spec.js
- test/unit/utils/needed-migrations-spec.js
- yarn.lock
> CLI Migrations

- test/unit/commands/log-spec.js
> chore(tests): add log command tests

- lib/index.js
- test/unit/index-spec.js
Not merging this yet - just had an idea on how to fix the issue and wanted to test it out.
> fix(extension): ensure require(ghost-cli) returns the root instance

- test/utils/env.js
This will make it possible for future tests to create a symlink to a file that's created in env.
> chore(tests): symlink after file creation

- lib/commands/setup.js
- test/unit/commands/setup-spec.js
> chore(test): implement setup command

- test/unit/commands/start-spec.js
> chore(tests): add tests for start command

- lib/commands/stop.js
- test/unit/commands/stop-spec.js
refs #541 
Also fixed a minor key typo for extension option configuration (merge both commits)
> chore(tests): add tests for stop command

- test/unit/commands/uninstall-spec.js
> chore(tests): add uninstall command tests

- lib/commands/setup.js
- test/unit/command-spec.js
- test/unit/commands/log-spec.js
- test/unit/commands/update-spec.js
- test/unit/ui/index-spec.js
- test/unit/ui/renderer-spec.js
> chore(lint) fix linting errors

- .github/ISSUE_TEMPLATE.md
> feat(issue template) update issue template to reflect readme changes

- extensions/nginx/test/extension-spec.js
refs #541  - see [comment](https://github.com/TryGhost/Ghost-CLI/issues/541#issuecomment-361513383)
cc @AileenCGN - can you check that this fixes the problem? I'm 95% sure it will 😄
> fix(nginx tests): stub OS for migration skip tests

- extensions/nginx/test/acme-spec.js
- lib/errors.js
- lib/tasks/migrate.js
- test/unit/tasks/migrate-spec.js
closes #562
- be able to pass a command suggestion
- added basic toString fn to error module
> feat(log): Log improvements for `ghost update` 

- lib/command.js
- lib/commands/doctor/checks/startup.js
- lib/commands/log.js
- lib/commands/stop.js
- lib/utils/check-valid-install.js
- test/unit/bootstrap-spec.js
- test/unit/command-spec.js
- test/unit/commands/doctor/startup-spec.js
- test/unit/commands/log-spec.js
- test/unit/commands/stop-spec.js
- test/unit/utils/check-root-user-spec.js
- test/unit/utils/check-valid-install-spec.js
no issue
- general code/test cleanup
> chore(util): move check-valid-install out into separate util

- lib/commands/setup.js
no issue
- noticed this when testing #607
> fix(setup): skip ghost user setup if process manager is local

- lib/ui/index.js
- test/unit/ui/index-spec.js
no issue
- this allows certain places to run multiple listr checks at once and have the ui class handle any resulting errors
> feat(ui): allow UI error method to handle listr errors

- lib/commands/doctor/checks/content-folder.js
- lib/commands/doctor/checks/folder-permissions.js
- lib/commands/doctor/checks/node-version.js
- lib/commands/update.js
- test/unit/commands/update-spec.js
> feat(update): run doctor checks on ghost update

- bin/ghost
- lib/bootstrap.js
- package.json
- test/fixtures/classes/test-invalid-command.js
- test/fixtures/classes/test-valid-command.js
- test/unit/bootstrap-spec.js
- yarn.lock
refs #541
- rework bootstrap file to be more unit-testable
- remove unneeded rewire dependency
> chore(tests): add tests for bootstrap

- extensions/systemd/test/systemd-spec.js
- lib/commands/doctor/index.js
- lib/errors.js
- lib/instance.js
- lib/process-manager.js
- lib/ui/index.js
- lib/utils/local-process.js
- test/fixtures/TestExtension/index.js
- test/unit/command-spec.js
- test/unit/commands/config-spec.js
- test/unit/commands/doctor/command-spec.js
- test/unit/commands/log-spec.js
- test/unit/errors-spec.js
- test/unit/extension-spec.js
- test/unit/tasks/yarn-install-spec.js
- test/unit/ui/index-spec.js
- test/unit/utils/find-extensions-spec.js
- test/unit/utils/get-os-spec.js
- test/unit/utils/resolve-version-spec.js
- test/unit/utils/yarn-spec.js
refs + closes #541 
All that's left right now is finishing bootstrap tests 😄
> [WIP] Finish Tests 💯🎉

- lib/commands/doctor/checks/file-permissions.js
- lib/commands/doctor/checks/folder-permissions.js
- test/unit/commands/doctor/checks/file-permissions-spec.js
- test/unit/commands/doctor/checks/folder-permissions-spec.js
- test/unit/utils/resolve-version-spec.js
no issue
simplify the way we check for `enabled` in file and folder permission checks
> feat(doctor) simplify enabled conditions

- lib/commands/doctor/index.js
- test/unit/commands/doctor/command-spec.js
> feat(doctor): allow extensions to provide doctor checks

- lib/commands/doctor/checks/check-permissions.js
- test/unit/commands/doctor/checks/content-folder-spec.js
- test/unit/commands/doctor/checks/file-permissions-spec.js
- test/unit/commands/doctor/checks/folder-permissions-spec.js
no issue
- improve error message and tests for permissions checks, when permission denied
> feat(doctor): improve permission denied error message

- lib/commands/doctor/checks/check-permissions.js
- test/unit/commands/doctor/checks/check-permissions-spec.js
- test/unit/commands/doctor/checks/file-permissions-spec.js
> fix(doctor): exclude versions folder for file permissions check

- extensions/mysql/index.js
- extensions/mysql/test/extension-spec.js
closes #642
- use % rather than the db host if host isn't localhost
TODO:
> fix(mysql): use % during user creation if remote db host

- lib/commands/doctor/checks/check-memory.js
- lib/commands/doctor/checks/index.js
- lib/commands/doctor/index.js
- lib/commands/install.js
- lib/commands/start.js
- lib/commands/update.js
- test/unit/commands/doctor/checks/check-memory-spec.js
- test/unit/commands/install-spec.js
- test/unit/commands/start-spec.js
- test/unit/commands/update-spec.js
> feat(startup checks): Ensure enough memory is available before starting

- lib/bootstrap.js
- lib/ui/pretty-stream.js
refs + closes #457 
depends on TryGhost/Ignition#53 (and assumes patch 19 will be released)
> feat(colors): Expose color-free logging option & add full support

- lib/ui/index.js
- lib/ui/renderer.js
- test/unit/ui/index-spec.js
- test/unit/ui/renderer-spec.js
- simplify how UI creates a renderer class, and how the renderer class maintains that UI instance
- simplify renderer tests
> refactor(ui): simplify interactions between ui + renderer

- lib/tasks/major-update/ui.js
Missing slash breaks the link.
> Separate URI Path and Domain

- lib/utils/resolve-version.js
- test/unit/utils/resolve-version-spec.js
refs https://forum.ghost.org/t/error-when-attempting-update-to-ghost-2-x/2515
> fix(version-resolver): allow v2 updates w/ multiple v2 releases

- lib/commands/doctor/checks/check-permissions.js
- test/unit/commands/doctor/checks/check-permissions-spec.js
closes #801
- set maxBuffer size to infinity
> fix(doctor): set find maxBuffer to infinity

- lib/bootstrap.js
- lib/command.js
- lib/commands/config/index.js
- lib/ui/index.js
- test/unit/command-spec.js
- test/unit/commands/config-spec.js
- test/unit/ui/index-spec.js
> feat: add --auto flag to make setup quicker

- lib/instance.js
- lib/system.js
- lib/ui/index.js
- lib/ui/renderer.js
- test/unit/instance-spec.js
- test/unit/system-spec.js
- test/unit/ui/index-spec.js
- test/unit/ui/renderer-spec.js
this is some side work that came out of #831, splitting it into a separate PR to make that PR smaller.
> add some small improvements to things

- .travis.yml
no issue
- add yarn audit to check for vulnerabilities
> chore(travis): run 'yarn audit' on lint build

- extensions/mysql/index.js
- extensions/mysql/test/extension-spec.js
- extensions/nginx/index.js
- extensions/nginx/test/extension-spec.js
- extensions/systemd/index.js
- extensions/systemd/test/extension-spec.js
- lib/commands/setup.js
- lib/tasks/linux.js
- test/unit/commands/setup-spec.js
> Refactor Setup Command (take 2)

- lib/tasks/yarn-install.js
- lib/utils/yarn.js
- package.json
- renovate.json
- test/unit/tasks/yarn-install-spec.js
- test/unit/utils/yarn-spec.js
- yarn.lock
no issue
- update rxjs version to 6
- use rxjs correctly in yarn utils (we weren't using it correctly before)
- refactor tests to work better with observable usage
> fix(deps): update rxjs to v6

- package.json
- renovate.json
- yarn.lock
- remove from renovate ignore list
> chore(deps): update fkill to v6.1.0

- lib/extension.js
- inquirer expects that the default you give it is the value, not the key, when it is a choice
> fix(extension): default should be value not key

- lib/ui/index.js
> fix(prompt): fix hasDefault check for --auto values

- package.json
> chore(node): update minimum supported node version to v8.10

- lib/tasks/yarn-install.js
- lib/utils/yarn.js
- test/unit/tasks/yarn-install-spec.js
- test/unit/utils/yarn-spec.js
refs #1036
- move verbose arg into yarn util
- report stderr to observer on verbose
> cleanup(yarn): move verbose handling into yarn util

- lib/commands/config.js
- lib/commands/ls.js
- lib/commands/restart.js
- lib/commands/setup.js
- test/unit/commands/config-spec.js
- test/unit/commands/ls-spec.js
- test/unit/commands/restart-spec.js
- test/unit/commands/setup-spec.js
no issue
- refactor commands/tests to use async/await
> cleanup: refactor more commands to use async/await

- lib/commands/doctor/checks/binary-deps.js
- lib/commands/doctor/checks/index.js
- lib/commands/update.js
- lib/instance.js
- test/unit/commands/doctor/checks/binary-deps-spec.js
- test/unit/commands/update-spec.js
- test/unit/instance-spec.js
no issue
- checks if the node version has changed on start, to prevent issues with binary deps
> feat(doctor): add binary dependency check

- lib/commands/doctor/checks/validate-config.js
- lib/commands/log.js
- lib/commands/restart.js
- lib/commands/start.js
- lib/commands/stop.js
- lib/commands/uninstall.js
- lib/commands/update.js
- lib/instance.js
- lib/system.js
- test/unit/commands/doctor/checks/validate-config-spec.js
- test/unit/commands/log-spec.js
- test/unit/commands/restart-spec.js
- test/unit/commands/start-spec.js
- test/unit/commands/stop-spec.js
- test/unit/commands/uninstall-spec.js
- test/unit/commands/update-spec.js
- test/unit/instance-spec.js
- test/unit/system-spec.js
no issue
- current behavior was a bit odd, this splits things out to make things more clear
> refactor(instance): split out running method

- lib/commands/update.js
- test/unit/commands/update-spec.js
no issue
- refactor command/tests to use async/await
- remove runCommand usage for start/stop
> refactor(update): refactor update command

- lib/commands/export.js
- lib/tasks/import/index.js
- lib/tasks/import/tasks.js
- test/unit/commands/export-spec.js
- test/unit/commands/import-spec.js
- test/unit/tasks/import/tasks-spec.js
> feat(export): add export command

- lib/utils/local-process.js
- test/unit/utils/local-process-spec.js
Tests are broken, but I'd like to get a logic review first 😄
> fix(local-process) output Ghost error message when process exits

- lib/commands/doctor/checks/check-memory.js
- test/unit/commands/doctor/checks/check-memory-spec.js
closes #1185
- add swapfree to available to get estimated memory availability
> fix(memcheck): include free swap space in memory check

- lib/commands/doctor/index.js
- lib/commands/log.js
- lib/commands/stop.js
- test/unit/commands/doctor/command-spec.js
- test/unit/commands/log-spec.js
- test/unit/commands/stop-spec.js
closes https://github.com/TryGhost/Ghost-CLI/issues/1223
- replace usages of checkValidInstall with findValidInstall
> fix: update usages of check-valid-install

- lib/commands/install.js
- test/unit/commands/install-spec.js
closes https://github.com/TryGhost/Ghost-CLI/issues/1218
> feat(install): add force flag to allow install in non-empty directory

- lib/tasks/major-update/ui.js
closes https://github.com/TryGhost/Ghost-CLI/issues/1116
> fix(major-update): make theme demo prompt dynamic

- package.json
- this is technically the most recent minor version
> fix(node): bump minimum supported node to 14.13

- lib/commands/doctor/checks/system-stack.js
- test/unit/commands/doctor/checks/system-stack-spec.js
refs #853,#1265
- refactor system stack check to use systeminformation to check support
- update ubuntu allowed versions to support Ubuntu 20
> feat(stack): refactor stack check & allow ubuntu 20

- .github/workflows/e2e-test.yml
these will start working when #1318 and #1319 are merged in
> feat(ci): add end-to-end github actions tests for standard stack

- extensions/nginx/index.js
Suggested change based on:
https://www.sanderverbruggen.com/installing-ghost-with-ssl-on-a-raspberry-pi/
> Update SSL cert parameters

- lib/tasks/release-notes.js
- test/unit/tasks/release-notes-spec.js
Also adds a 'lil perf improvement 💨 w/ tests!
> fix(release-notes): add support for 4.x+ tag names

- extensions/systemd/doctor.js
- extensions/systemd/index.js
- extensions/systemd/test/doctor-spec.js
- lib/commands/doctor/checks/node-version.js
- package.json
- test/unit/commands/doctor/checks/node-version-spec.js
- yarn.lock
needs tests but wanted to get initial feedback/testing
> Log Node Version from doctor checks

- lib/utils/pre-checks.js
- test/unit/utils/pre-checks-spec.js
no issue
- refactor code to be more easily testable
- use async/await in code & tests
> refactor(pre): cleanup pre-checks with async/await

- lib/commands/start.js
- test/unit/commands/start-spec.js
- closes #863 
- one test is failing because it's an edge case and I'm not sure if it should be handled
> chore(start): show warning for insecure URLs in production

- CHANGELOG.md
- lib/commands/start.js
- lib/instance.js
- lib/utils/deprecation-checks.js
- package.json
- test/unit/commands/start-spec.js
- test/unit/instance-spec.js
going forward, gonna just backport main fixes to 1.x so I don't have to do this again
> Cherry-picked fixes from v1.x branch

- .github/workflows/e2e-test.yml
- .github/workflows/unit-test.yml
refs https://github.com/TryGhost/Ghost-CLI/pull/1595#discussion_r795005761
see https://togithub.com/actions/setup-node#caching-packages-dependencies
> chore(actions): enable yarn dependency caching

- lib/command.js
- test/unit/command-spec.js
refs https://github.com/TryGhost/Toolbox/issues/225
- this commit adds a notice about joining the Ghost team to the CLI that
should run for every command
> feat(cmd): added notice about joining the Ghost team

- lib/commands/backup.js
- lib/tasks/backup.js
> Added `ghost backup` command

- lib/commands/backup.js
Please see individual commits: https://github.com/TryGhost/Ghost-CLI/pull/1640/commits
> Minor fixes for backup command

- .github/workflows/e2e-test.yml
- .github/workflows/local-e2e-test.yml
- .github/workflows/unit-test.yml
* Discovered in https://github.com/TryGhost/Ghost-CLI/pull/1813
* Configured to align with https://ghost.org/docs/faq/node-versions/
> Update node versions in CI

- lib/tasks/import/api-auth-strategies.js
- lib/tasks/import/api.js
- lib/tasks/import/tasks.js
- test/unit/tasks/import/api-spec.js
> Minor refactor/cleanups around backup auth

- lib/tasks/import/api-auth-strategies.js
- lib/tasks/import/api.js
- lib/tasks/import/tasks.js
- package.json
- test/unit/tasks/import/api-spec.js
- test/unit/tasks/import/tasks-spec.js
- yarn.lock
> :bug: fixed broken backups on newer Ghost versions

- extensions/nginx/templates/nginx-ssl.conf
- extensions/nginx/templates/nginx.conf
ref no-issue
- Changed nginx templates to add activitypub paths for Ghost.
> Added activitypub path to nginx

- lib/commands/doctor/checks/system-stack.js
- test/unit/commands/doctor/checks/system-stack-spec.js
> chore(os): add warning for EoL Ubuntu versions
